"""ubs_core.py_scan — contract-v2 orchestrator for the Python module (bead 0xjg.5).

ONE ``python3 -m ubs_core.py_scan`` process replaces the legacy module's
~250-400 process spawns (57 rg pipelines, 37 python heredocs, ~156 ast-grep
invocations). Layers, in legacy-equivalent order:

1. ``ubs_core.py_patterns.*``  Pattern tables — faithful ports of the legacy
   rg pipelines (category-scoped regex + threshold-descending severity
   ladders; DISTINCT-LINE project-wide counting).
2. ``ubs_core.py_detectors.*`` Detector modules — ports of the legacy python
   heredoc detectors (AST walkers emitting per-detection records).
3. Registry analyzers (taint_py, lifecycle_py, guards_py, ctcompare_py) —
   already migrated in A2; ``python.narrowing.*`` (bead D4, no legacy
   counterpart) is disabled by default so v2 stays at legacy parity; opt in
   with ``--enable-new-analyzers``.
4. ``ubs_core.py_ast`` — the consolidated ast-grep rule pack (51 rules
   generated by ``ubs_core.py_rules``), one ``scan -c`` invocation per batch.

The NDJSON sink is the single source of truth: totals are recounted from it
(js parity), ``--json-out`` carries a run_lang-compatible summary object plus
the raw records and a legacy-shaped per-category report (issue-64 payload
with title/description/samples), and ``--text-out`` renders the legacy text
report. The bash caller appends record-less section headers and the final
"Summary Statistics:" block (see run_v2_legacy_parity_bridges_py).

Python 3.9+ stdlib only.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from ubs_core.lexer import strip_comments_and_strings
from ubs_core.registry import RunContext
from ubs_core.io import read_ndjson

MARKER = "ubs:ignore"

# Files whose text is a Python token stream (so string blanking is valid).
_PY_SUFFIXES = frozenset({".py", ".pyi"})

_CATEGORY_SLUGS = {
    1: "none", 2: "numeric", 3: "collections", 4: "comparison",
    5: "async", 6: "error-handling", 7: "security", 8: "functions",
    9: "parsing", 10: "control-flow", 11: "debug", 12: "perf",
    13: "variables", 14: "code-quality", 15: "regex", 16: "io",
    17: "typing", 18: "modules", 19: "resource-lifecycle", 20: "uv-tools",
    21: "deprecations", 22: "packaging", 23: "notebooks",
}

# Legacy print_header titles, in category order (rendered before a section).
_SECTION_HEADERS = {
    1: "1. NONE / DEFENSIVE PROGRAMMING",
    2: "2. NUMERIC / ARITHMETIC PITFALLS",
    3: "3. COLLECTION SAFETY",
    4: "4. COMPARISON & TYPE CHECKING TRAPS",
    5: "5. ASYNC/AWAIT PITFALLS",
    6: "6. ERROR HANDLING ANTI-PATTERNS",
    7: "7. SECURITY VULNERABILITIES",
    8: "8. FUNCTION & SCOPE ISSUES",
    9: "9. PARSING & TYPE CONVERSION BUGS",
    10: "10. CONTROL FLOW GOTCHAS",
    11: "11. DEBUGGING & PRODUCTION CODE",
    12: "12. PERFORMANCE & MEMORY",
    13: "13. VARIABLE & SCOPE",
    14: "14. CODE QUALITY MARKERS",
    15: "15. REGEX & STRING SAFETY",
    16: "16. I/O & RESOURCE SAFETY",
    17: "17. TYPING STRICTNESS",
    18: "18. PYTHON I/O & MODULE USAGE",
    19: "19. RESOURCE LIFECYCLE CORRELATION",
    20: "20. UV-POWERED EXTRA ANALYZERS",
    21: "21. DEPRECATIONS & PY3.13 MIGRATIONS",
    22: "22. PACKAGING & CONFIG HYGIENE",
    23: "23. NOTEBOOK HYGIENE",
}

# Legacy print_subheader texts that manifest cases assert, keyed by the rule
# prefix they announce (taint heredoc + SQL two-tier family).
_SUBHEADERS = {
    5: {"py.async.task-no-await": "Async error path coverage"},
    7: {
        "python.taint.": "Lightweight taint analysis",
        "py.taint.": "Lightweight taint analysis",
        "py.security.sql": "Interpolated SQL execution",
    },
}

# Rule id -> legacy print_finding title for analyzer/detector findings that
# carry their own message (SUMMARY_MAP). Pack findings embed "id: message" in
# the sink record already; pattern findings carry pattern titles.
_SUMMARY_TITLES: dict[str, str] = {
    # TAINT_SUMMARY (ubs-python.sh 173-178)
    "python.taint.xss": "Unsanitized request data reaches HTML/response sinks",
    "python.taint.sql": "User input flows into SQL execute() without parameters",
    "python.taint.command": "User input reaches subprocess/os.system",
    "python.taint.eval": "User input flows into eval/exec",
    # RESOURCE_LIFECYCLE_SUMMARY (394-399)
    "python.lifecycle.file_handle": "File handles opened without context manager/close",
    "python.lifecycle.socket_handle": "Sockets opened without matching close()",
    "python.lifecycle.popen_handle": "Popen handles not waited or terminated",
    "python.lifecycle.asyncio_task": "asyncio tasks spawned without cancellation/await",
    # ctcompare_py (GH #85 two-tier vocabulary)
    "python.ctcompare.secret_eq": "Secret, signature, or token compared with ==/!=",
    # guards_py (GH #90)
    "python.guards.deep_attr_chain": "Deep attribute chains without guards",
}


def slug_for_category(category: int) -> str:
    return _CATEGORY_SLUGS.get(category, f"cat{category}")


@dataclass(frozen=True)
class Pattern:
    """One legacy rg pipeline: a category-scoped regex with count thresholds.

    thresholds is a descending list of (min_count_exclusive, severity): the
    first entry whose count > min_count wins; when none match, the category
    reports nothing — mirroring the legacy `warning >15 / info >0` ladders.
    gate_regex expresses legacy project-wide preconditions;
    suppress_when_regex expresses count-comparison silences.

    Two precision controls sit on top of the legacy semantics:

    ``scan_strings`` — by default a pattern is matched against source with
    **string literals blanked out** (comments are kept, so marker rules such
    as py.code-quality.tech-debt still see `# TODO`). A rule whose evidence
    genuinely lives inside a literal — a regex source, a logged secret, a
    concatenated string — sets ``scan_strings=True`` to opt back into raw
    text. Blanking is offset-preserving, so line numbers never move, and the
    reported code sample is always taken from the raw line.

    ``exclude_file_regex`` — skip a whole file for this pattern when its raw
    text matches. Used for rules whose finding depends on the *role* of the
    module rather than the line (a CLI entry point prints by design).
    """

    category: int
    rule_id: str
    title: str
    regex: re.Pattern[str]
    thresholds: tuple[tuple[int, str], ...]
    case_insensitive: bool = False
    exclude_regex: re.Pattern[str] | None = None  # legacy `grep -v` post-filters
    gate_regex: re.Pattern[str] | None = None  # legacy project-wide precondition
    suppress_when_regex: re.Pattern[str] | None = None  # legacy project-wide silencer
    scan_strings: bool = False  # match inside string literals too
    exclude_file_regex: re.Pattern[str] | None = None  # skip files whose text matches


def iter_matches(
    pattern: Pattern, text: str, raw_text: str | None = None
) -> Iterable[tuple[int, str]]:
    """Yield (line_number, line_text) for matches, skipping excluded lines.

    ``text`` is what the regex runs against (string-blanked unless the pattern
    opted out); ``raw_text`` is the original source used for the ubs:ignore
    check, the exclude_regex post-filter and the reported code sample. Blanking
    preserves offsets, so both share one coordinate system.
    """
    source = raw_text if raw_text is not None else text
    for match in pattern.regex.finditer(text):
        line_no = text.count("\n", 0, match.start()) + 1
        line_start = source.rfind("\n", 0, match.start()) + 1
        line_end = source.find("\n", match.start())
        if line_end == -1:
            line_end = len(source)
        line_text = source[line_start:line_end]
        if MARKER in line_text:
            continue  # legacy count_lines drops marker lines from counts
        if pattern.exclude_regex is not None and pattern.exclude_regex.search(line_text):
            continue
        yield line_no, line_text.strip()[:240]


def resolve_severity(pattern: Pattern, count: int) -> str | None:
    for min_count, severity in pattern.thresholds:
        if count > min_count:
            return severity
    return None


def scan_patterns(
    patterns: Sequence[Pattern],
    files: Sequence[Path],
    sink,
    skip: set[int],
    prefilter: Any = None,
    jobs: int = 1,
) -> dict[str, int]:
    """Run every pattern over the file list, writing sink records.

    Legacy parity semantics: counts are DISTINCT MATCHING LINES across the
    whole file list (rg prints each matching line once), and severity is
    resolved ONCE per pattern from that project-wide count — every record of
    a pattern carries the same severity, so summed counters equal the legacy
    print_finding buckets.

    Python sources are matched with string literals blanked (comments kept)
    unless a pattern sets ``scan_strings``; see Pattern. Without that, a
    project that stores code snippets in literals — a linter's own rule
    tables, a template, a test fixture embedded as a string — has every
    snippet reported as if it were live code.

    Returns severity counters ({"critical": n, "warning": n, "info": n}).
    """
    counters = {"critical": 0, "warning": 0, "info": 0}
    active = [p for p in patterns if p.category not in skip]
    if not active:
        return counters

    def _read_text(p: Path) -> tuple[Path, str]:
        try:
            return p, p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            return p, ""

    if jobs > 1 and len(files) > 1:
        from ubs_core.shards import run_work_stealing

        pairs = run_work_stealing(files, lambda shard: [_read_text(p) for p in shard], num_workers=jobs)
        texts: dict[Path, str] = {p: t for p, t in pairs if t}
    else:
        texts = {}
        for path in files:
            try:
                texts[path] = path.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
    masked: dict[Path, str] = {}

    def _scan_text(path: Path, text: str) -> str:
        """String-blanked view of a Python source, comments preserved."""
        if path.suffix.lower() not in _PY_SUFFIXES:
            return text  # notebooks/requirements are not Python token streams
        cached = masked.get(path)
        if cached is None:
            try:
                cached = strip_comments_and_strings(
                    text, lang="python", strip_strings=True,
                    strip_comments=True, preserve_comments=True,
                )
            except Exception:  # a masker failure must not lose the rule
                cached = text
            masked[path] = cached
        return cached

    for pattern in active:
        if pattern.gate_regex is not None and not any(
            pattern.gate_regex.search(text) for text in texts.values()
        ):
            continue
        if pattern.suppress_when_regex is not None and any(
            pattern.suppress_when_regex.search(text) for text in texts.values()
        ):
            continue
        hits: list[tuple[Path, int, str]] = []
        seen: set[tuple[Path, int]] = set()
        for path, text in texts.items():
            if prefilter is not None and pattern.rule_id not in prefilter.candidate_rules_for(path):
                continue
            if pattern.exclude_file_regex is not None and pattern.exclude_file_regex.search(text):
                continue
            scan_text = text if pattern.scan_strings else _scan_text(path, text)
            for line_no, line_text in iter_matches(pattern, scan_text, text):
                key = (path, line_no)
                if key in seen:
                    continue
                seen.add(key)
                hits.append((path, line_no, line_text))
        if not hits:
            continue
        severity = resolve_severity(pattern, len(hits))
        if severity is None:
            continue
        counters[severity] = counters.get(severity, 0) + len(hits)
        for path, line_no, line_text in hits:
            sink.write(json.dumps({
                "rule": pattern.rule_id,
                "category_id": f"python.{slug_for_category(pattern.category)}",
                "path": str(path),
                "line": line_no,
                "col": 1,
                "severity": severity,
                "message": f"{pattern.title} — {line_text}",
                "suppressed": False,
            }, ensure_ascii=False) + "\n")
    return counters


def load_patterns() -> list[Pattern]:
    """Aggregate PATTERNS from every ubs_core.py_patterns.* module."""
    import importlib
    import pkgutil

    from ubs_core import py_patterns

    patterns: list[Pattern] = []
    for module_info in pkgutil.iter_modules(py_patterns.__path__):
        if module_info.name.startswith("_"):
            continue
        try:
            module = importlib.import_module(f"ubs_core.py_patterns.{module_info.name}")
        except Exception as exc:  # a broken pattern module must not kill the scan
            sys.stderr.write(f"[ubs_core.py_scan] pattern module {module_info.name} failed: {exc}\n")
            continue
        patterns.extend(getattr(module, "PATTERNS", []))
    return patterns


def _record_category(finding: dict) -> int | None:
    """Map a finding's rule id to its legacy category number."""
    rule = str(finding.get("rule", ""))
    category_id = str(finding.get("category_id", ""))
    # Registry analyzers (A2) — legacy heredocs ran inside their categories.
    if rule.startswith(("python.taint.", "python.ctcompare.", "py.taint.", "py.security.")):
        return 7
    if rule.startswith("python.lifecycle."):
        return 19
    if rule.startswith("python.guards."):
        return 1
    # category_id is authoritative for pattern/detector records.
    for num, slug in _CATEGORY_SLUGS.items():
        if category_id == f"python.{slug}":
            return num
    # Legacy `py.<slug>.<name>` ids minted after the meta-runner slug table.
    if rule.startswith("py."):
        rest = rule[3:]
        for num, slug in _CATEGORY_SLUGS.items():
            if rest.startswith(f"{slug}."):
                return num
        # Pack metadata ids (run_async_error_checks, ubs-python.sh 159-169).
        if rule == "py.async.task-no-await":
            return 5
    return None  # ast-pack rules count in totals only (legacy CURRENT_CATEGORY=0)


def run_analyzers(
    files: Sequence[Path],
    sink,
    skip: set[int] | None = None,
    enable_new: bool = False,
    prefilter: Any = None,
) -> None:
    """Run registered python analyzers (taint, lifecycle, guards, ctcompare).

    ``python.narrowing.*`` (bead D4) has no legacy python counterpart — it
    stays off unless ``enable_new`` is set, so v2 totals match legacy.
    """
    from ubs_core import analyzers  # noqa: F401  (populate registry)
    from ubs_core.registry import analyzers_for_lang

    for analyzer in analyzers_for_lang("python"):
        if analyzer.layer == "narrowing" and not enable_new:
            continue
        if prefilter is not None:
            target_files = prefilter.filter_files_for_analyzer(analyzer.name, files)
        else:
            target_files = list(files)
        if not target_files:
            continue
        ctx = RunContext(lang="python", files=target_files)
        for finding in analyzer.run(ctx):
            if skip and _record_category(finding) in skip:
                continue
            sink.write(json.dumps({
                "rule": finding.get("rule", ""),
                "category_id": finding.get("category_id", "python.security"),
                "path": finding.get("path", ""),
                "line": int(finding.get("line", 0) or 0),
                "col": int(finding.get("col", 1) or 1),
                "severity": finding.get("severity", "warning"),
                "message": finding.get("message", ""),
                "suppressed": False,
            }, ensure_ascii=False) + "\n")


def run_detectors(files: Sequence[Path], sink, skip: set[int] | None = None) -> None:
    """Run ubs_core.py_detectors.* modules (legacy heredoc detector ports).

    Protocol (single-rule modules): RULE_ID, CATEGORY, TITLE, SEVERITY,
    DESCRIPTION and ``find(files)`` yielding (path, line, col, detail).
    Multi-rule modules (e.g. the SQL two-tier detector) expose ``RULES`` —
    a tuple of (rule_id, category, title, severity, description) tuples —
    and ``find(files)`` yielding (rule_id, path, line, col, detail).
    """
    import importlib
    import pkgutil

    from ubs_core import py_detectors

    for module_info in pkgutil.iter_modules(py_detectors.__path__):
        if module_info.name.startswith("_"):
            continue
        try:
            module = importlib.import_module(f"ubs_core.py_detectors.{module_info.name}")
        except Exception as exc:  # legacy heredoc failures degraded gracefully too
            sys.stderr.write(f"[ubs_core.py_scan] detector module {module_info.name} failed: {exc}\n")
            continue
        find = getattr(module, "find", None)
        if find is None:
            continue
        if hasattr(module, "RULES"):
            specs = {
                spec[0]: {"category": int(spec[1]), "title": str(spec[2]),
                          "severity": str(spec[3]), "description": str(spec[4])}
                for spec in module.RULES
            }
        else:
            category = int(getattr(module, "CATEGORY", 7))
            rule_id = str(getattr(module, "RULE_ID", f"py.cat{category}.{module_info.name}"))
            specs = {rule_id: {
                "category": category,
                "title": str(getattr(module, "TITLE", rule_id)),
                "severity": str(getattr(module, "SEVERITY", "warning")),
                "description": str(getattr(module, "DESCRIPTION", "")),
            }}
        if skip:
            specs = {rid: spec for rid, spec in specs.items()
                     if spec["category"] not in skip}
            if not specs:
                continue
        for hit in find(files):
            if len(hit) == 5:
                rule_id, path, line_no, col, detail = hit
            else:
                path, line_no, col, detail = hit  # single-rule convenience
                rule_id = next(iter(specs))
            spec = specs.get(rule_id)
            if spec is None:
                continue
            slug = slug_for_category(spec["category"])
            title = spec["title"]
            sink.write(json.dumps({
                "rule": rule_id,
                "category_id": f"python.{slug}",
                "path": str(path),
                "line": int(line_no),
                "col": int(col),
                "severity": spec["severity"],
                "message": f"{title} — {detail}"[:300] if detail else title,
                "suppressed": False,
            }, ensure_ascii=False) + "\n")


def _finding_title(rec: dict) -> str:
    rule = rec.get("rule", "")
    if rule in _SUMMARY_TITLES:
        return _SUMMARY_TITLES[rule]
    return str(rec.get("message", rule))


def _sample_code(path: str, line_no: int) -> str:
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            for i, line in enumerate(fh, 1):
                if i == line_no:
                    return line.strip()[:200]
    except OSError:
        pass
    return ""


def _legacy_report(records: list[dict], version: str) -> dict:
    """Legacy --report-json payload (issue-64): per-rule aggregated findings
    with severity/count/title/description and up to 3 code samples."""
    by_rule: dict[str, list[dict]] = {}
    for rec in records:
        by_rule.setdefault(rec.get("rule", ""), []).append(rec)
    findings = []
    for rule, recs in by_rule.items():
        first = recs[0]
        samples = []
        for rec in recs[:3]:
            samples.append({
                "file": rec.get("path", ""),
                "line": int(rec.get("line", 0) or 0),
                "code": _sample_code(rec.get("path", ""), int(rec.get("line", 0) or 0)),
            })
        findings.append({
            "rule": rule,
            "rule_id": rule,
            "severity": first.get("severity", "info"),
            "count": len(recs),
            "title": _finding_title(first),
            "description": "",
            "samples": samples,
        })
    return {"version": version, "findings": findings}


def _render_text(args, files: Sequence[Path], counters: dict[str, int]) -> None:
    """Render the legacy-format text report from the NDJSON sink."""
    import datetime

    records = read_ndjson(args.sink)
    by_rule: dict[str, list[dict]] = {}
    for rec in records:
        by_rule.setdefault(rec["rule"], []).append(rec)

    lines = [
        f"UBS module: python (contract v2) — {args.project or args.project_dir}",
        f"Files scanned: {len(files)}",
    ]
    category_order = {num: i for i, num in enumerate(sorted(_CATEGORY_SLUGS))}
    ordered_rules = sorted(
        by_rule,
        key=lambda rule: (
            category_order.get(_record_category(by_rule[rule][0]) or 99, 99),
            rule,
        ),
    )
    current_section = None
    emitted_subheaders: set[str] = set()
    for rule in ordered_rules:
        recs = by_rule[rule]
        category_num = _record_category(recs[0])
        section = _SECTION_HEADERS.get(category_num) if category_num is not None else None
        subheader = None
        if category_num is not None:
            for prefix, text in _SUBHEADERS.get(category_num, {}).items():
                if rule.startswith(prefix) or str(recs[0].get("category_id", "")).startswith(prefix):
                    subheader = text
        if section is not None and section != current_section:
            lines.append("")
            lines.append(section)
            current_section = section
        if subheader and subheader not in emitted_subheaders:
            lines.append(subheader)
            emitted_subheaders.add(subheader)
        if section is None and current_section != "AST-GREP RULE PACK FINDINGS":
            # Legacy pack findings printed under their own header (11439)
            # and counted in totals only (CURRENT_CATEGORY=0).
            lines.append("")
            lines.append("AST-GREP RULE PACK FINDINGS")
            lines.append("ast-grep rule-pack summary")
            current_section = "AST-GREP RULE PACK FINDINGS"
        severity = recs[0]["severity"]
        title = _finding_title(recs[0])
        lines.append(f"[{severity}] {title} ({len(recs)} found) — {rule}")
        cap = 25 if rule.endswith("sql-injection") else 5
        for rec in recs[:cap]:
            lines.append(f"    {rec['path']}:{rec['line']}  {str(rec.get('message', ''))[:180]}")

    # Legacy "good" notes for emit groups whose category produced no findings.
    categories_with_records = {
        _record_category(rec) for rec in records
    }
    good_notes = {
        19: "All tracked resource acquisitions have matching cleanups",
        5: "All async operations appear protected",
        4: "No 'is' literal comparisons",
    }
    for num, note in good_notes.items():
        if num not in categories_with_records and num not in _skip_set(args):
            lines.append(f"good: {note}")

    lines += [
        f"Critical issues: {counters['critical']}",
        f"Warning issues: {counters['warning']}",
        f"Info items: {counters['info']}",
        f"Report generated: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
    ]
    Path(args.text_out).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _skip_set(args) -> set[int]:
    return {int(part) for part in (args.skip or "").split(",") if part.strip().isdigit()}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python3 -m ubs_core.py_scan")
    parser.add_argument("--files-from", default="-", help="NUL-separated file list ('-' = stdin)")
    parser.add_argument("--sink", required=True, help="NDJSON findings sink path")
    parser.add_argument("--project-dir", default="", help="base dir for relative sink paths")
    parser.add_argument("--skip", default="", help="comma-separated category numbers to skip")
    parser.add_argument("--ast-rule-dir", default="", help="consolidated ast-grep rule dir (sgconfig-*.yml + manifest.json)")
    parser.add_argument("--text-out", default="", help="write the legacy-format text report here")
    parser.add_argument("--json-out", default="", help="write the UBS summary JSON document here")
    parser.add_argument("--project", default="", help="project path recorded in the json summary")
    parser.add_argument("--version", default="", help="module version recorded in the json summary")
    parser.add_argument("--fail-on-warning", action="store_true")
    parser.add_argument("--jobs", type=int, default=1, help="parallel worker count for work-stealing file shards")
    parser.add_argument("--enable-new-analyzers", action="store_true",
                        help="run analyzers with no legacy counterpart (python.narrowing)")
    args = parser.parse_args(argv)

    if args.files_from in ("-", ""):
        data = sys.stdin.buffer.read()
    else:
        data = Path(args.files_from).read_bytes()
    entries = data.split(b"\0") if b"\0" in data else data.splitlines()
    files = [Path(raw.decode("utf-8", "surrogateescape")) for raw in entries if raw.strip()]
    skip = _skip_set(args)

    patterns = load_patterns()
    from ubs_core.cache import CapturingSink, ScanCache

    cache = ScanCache(
        lang="python",
        project_dir=args.project_dir or args.project or ".",
        skip=args.skip,
        custom_rules=args.ast_rule_dir,
        extra=f"new_analyzers={args.enable_new_analyzers}",
    )
    cached_findings, files_to_scan = cache.partition_files(files)

    capturing_sink = None
    if files_to_scan:
        from ubs_core.py_rules import _RULES
        from ubs_core.prefilter import build_prefilter_index, run_prefilter
        from ubs_core.registry import analyzers_for_lang
        from ubs_core import analyzers  # noqa: F401

        py_analyzers = [a.name for a in analyzers_for_lang("python")]
        ast_rules_input = list(_RULES)
        if args.ast_rule_dir:
            rules_dir = Path(args.ast_rule_dir) / "rules"
            if rules_dir.is_dir():
                for rf in rules_dir.glob("*.yml"):
                    try:
                        text = rf.read_text(encoding="utf-8", errors="ignore")
                        id_m = re.search(r"id:\s*(\S+)", text)
                        rid = id_m.group(1) if id_m else rf.stem
                        ast_rules_input.append((rid, text))
                    except OSError:
                        pass

        prefilter_index = build_prefilter_index(
            ast_rules=ast_rules_input,
            patterns=patterns,
            analyzers=py_analyzers,
            lang="py",
        )
        prefilter_res = run_prefilter(files_to_scan, prefilter_index)

        capturing_sink = CapturingSink()
        counters = scan_patterns(patterns, files_to_scan, capturing_sink, skip, prefilter=prefilter_res, jobs=args.jobs)
        run_detectors(files_to_scan, capturing_sink, skip)
        run_analyzers(files_to_scan, capturing_sink, skip, enable_new=args.enable_new_analyzers, prefilter=prefilter_res)
        if args.ast_rule_dir:
            from ubs_core.py_ast import scan_all
            from ubs_core.py_rules import CATEGORY_MAP, SEVERITY_MAP

            overrides: dict[str, str] = dict(SEVERITY_MAP)
            manifest_path = Path(args.ast_rule_dir) / "manifest.json"
            if manifest_path.is_file():
                try:
                    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                    for rid, meta in manifest.items():
                        if isinstance(meta, dict) and meta.get("severity") and rid not in overrides:
                            overrides[rid] = meta["severity"]
                except (ValueError, OSError):
                    pass
            ast_files = prefilter_res.ast_files if not prefilter_res.is_bypass else files_to_scan
            scan_all(
                Path(args.ast_rule_dir), ast_files, capturing_sink, overrides,
                count_only=None, skip_categories=None, category_map=CATEGORY_MAP,
                skip=skip,
            )
        cache.store_scanned_files(files_to_scan, capturing_sink.by_file)
    else:
        from ubs_core.prefilter import PrefilterResult
        prefilter_res = PrefilterResult(
            files_considered=0,
            files_after_prefilter=0,
            prefilter_ms=0,
            is_bypass=False,
        )

    prefilter_file = os.environ.get("UBS_PREFILTER_FILE")
    if prefilter_file:
        try:
            Path(prefilter_file).write_text(json.dumps(prefilter_res.to_dict()), encoding="utf-8")
        except OSError:
            pass

    all_recs: list[dict] = []
    for f in files:
        recs = cached_findings.get(f)
        if recs is None and capturing_sink is not None:
            recs = capturing_sink.get_for_file(f, project_dir=args.project_dir or args.project)
        if recs:
            all_recs.extend(recs)

    # Reconcile threshold-ladder patterns against current scan counts
    pattern_by_id = {p.rule_id: p for p in patterns if any(min_count > 0 for min_count, _ in p.thresholds)}
    if pattern_by_id:
        counts_by_rule: dict[str, int] = {}
        for r in all_recs:
            rid = r.get("rule", "")
            if rid in pattern_by_id:
                counts_by_rule[rid] = counts_by_rule.get(rid, 0) + 1

        filtered_recs: list[dict] = []
        for r in all_recs:
            rid = r.get("rule", "")
            if rid in pattern_by_id:
                sev = resolve_severity(pattern_by_id[rid], counts_by_rule.get(rid, 0))
                if sev is None:
                    continue  # Threshold not met in current file set
                r["severity"] = sev
            filtered_recs.append(r)
        all_recs = filtered_recs

    with open(args.sink, "w", encoding="utf-8") as sink_file:
        for r in all_recs:
            sink_file.write(json.dumps(r, ensure_ascii=False) + "\n")

    cache_file = os.environ.get("UBS_CACHE_FILE") or (os.path.splitext(args.sink)[0] + ".cache")
    cache.write_stats(cache_file)

    # The sink is the single source of truth: recount severities from it so
    # every layer (patterns, detectors, analyzers, ast) is reflected in totals.
    counters = {"critical": 0, "warning": 0, "info": 0}
    for line in Path(args.sink).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            severity = json.loads(line).get("severity", "info")
        except ValueError:
            continue
        counters[severity] = counters.get(severity, 0) + 1

    exit_code = 1 if counters["critical"] else 0
    if args.fail_on_warning and (counters["critical"] + counters["warning"]) > 0:
        exit_code = 1

    if args.json_out:
        records = read_ndjson(args.sink)
        import datetime

        legacy_findings = _legacy_report(records, args.version)["findings"]
        doc = {
            "language": "python",
            "project": args.project or args.project_dir,
            "timestamp": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "files": len(files),
            "critical": counters["critical"],
            "warning": counters["warning"],
            "info": counters["info"],
            "version": args.version,
            "status": "ok",
            "findings": legacy_findings,
            # Legacy issue-64 payload (title + samples) carried inside the
            # module summary so the combined JSON keeps per-finding samples.
            "report": {"version": args.version, "findings": legacy_findings},
        }
        profile_data = {
            "files_considered": prefilter_res.files_considered if files_to_scan else len(files),
            "files_after_prefilter": prefilter_res.files_after_prefilter if files_to_scan else 0,
            "prefilter_ms": prefilter_res.prefilter_ms if files_to_scan else 0,
            "cache_hits": cache.stats["hits"],
            "cache_misses": cache.stats["misses"],
            "cache_hit_rate": cache.stats["hit_rate"],
        }
        if os.environ.get("UBS_PROFILE") == "1":
            doc["profile"] = profile_data
        extras = doc.get("extras", {}) if isinstance(doc.get("extras"), dict) else {}
        extras["profile"] = profile_data
        doc["extras"] = extras
        Path(args.json_out).write_text(json.dumps(doc, ensure_ascii=False) + "\n", encoding="utf-8")

    if args.text_out:
        _render_text(args, files, counters)

    sys.stderr.write(json.dumps({
        "counters": counters,
        "patterns": len(patterns),
        "prefilter": prefilter_res.to_dict(),
        "cache": cache.stats,
    }) + "\n")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
