"""ubs_core.py_scan — contract-v2 orchestrator for the Python module (bead 0xjg.5).

ONE ``python3 -m ubs_core.py_scan`` process replaces the legacy module's
~250-400 process spawns (57 rg pipelines, 37 python heredocs, ~156 ast-grep
invocations). Layers, in legacy-equivalent order:

1. ``ubs_core.py_patterns.*``  Pattern tables — faithful ports of the legacy
   rg pipelines (category-scoped regex + threshold-descending severity
   ladders; DISTINCT-LINE project-wide counting).
2. ``ubs_core.py_detectors.*`` Detector modules — ports of the legacy python
   heredoc detectors (AST walkers emitting per-detection records).
3. Registry analyzers (taint_py, lifecycle_py, guards_py, ctcompare_py) —
   already migrated in A2; ``python.narrowing.*`` (bead D4, no legacy
   counterpart) is disabled by default so v2 stays at legacy parity; opt in
   with ``--enable-new-analyzers``.
4. ``ubs_core.py_ast`` — the consolidated ast-grep rule pack (51 rules
   generated by ``ubs_core.py_rules``), one ``scan -c`` invocation per batch.

The NDJSON sink is the single source of truth: totals are recounted from it
(js parity), ``--json-out`` carries a run_lang-compatible summary object plus
the raw records and a legacy-shaped per-category report (issue-64 payload
with title/description/samples), and ``--text-out`` renders the legacy text
report. The bash caller appends record-less section headers and the final
"Summary Statistics:" block (see run_v2_legacy_parity_bridges_py).

Python 3.9+ stdlib only.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

from ubs_core.registry import RunContext

MARKER = "ubs:ignore"

_CATEGORY_SLUGS = {
    1: "none", 2: "numeric", 3: "collections", 4: "comparison",
    5: "async", 6: "error-handling", 7: "security", 8: "functions",
    9: "parsing", 10: "control-flow", 11: "debug", 12: "perf",
    13: "variables", 14: "code-quality", 15: "regex", 16: "io",
    17: "typing", 18: "modules", 19: "resource-lifecycle", 20: "uv-tools",
    21: "deprecations", 22: "packaging", 23: "notebooks",
}

# Legacy print_header titles, in category order (rendered before a section).
_SECTION_HEADERS = {
    1: "1. NONE / DEFENSIVE PROGRAMMING",
    2: "2. NUMERIC / ARITHMETIC PITFALLS",
    3: "3. COLLECTION SAFETY",
    4: "4. COMPARISON & TYPE CHECKING TRAPS",
    5: "5. ASYNC/AWAIT PITFALLS",
    6: "6. ERROR HANDLING ANTI-PATTERNS",
    7: "7. SECURITY VULNERABILITIES",
    8: "8. FUNCTION & SCOPE ISSUES",
    9: "9. PARSING & TYPE CONVERSION BUGS",
    10: "10. CONTROL FLOW GOTCHAS",
    11: "11. DEBUGGING & PRODUCTION CODE",
    12: "12. PERFORMANCE & MEMORY",
    13: "13. VARIABLE & SCOPE",
    14: "14. CODE QUALITY MARKERS",
    15: "15. REGEX & STRING SAFETY",
    16: "16. I/O & RESOURCE SAFETY",
    17: "17. TYPING STRICTNESS",
    18: "18. PYTHON I/O & MODULE USAGE",
    19: "19. RESOURCE LIFECYCLE CORRELATION",
    20: "20. UV-POWERED EXTRA ANALYZERS",
    21: "21. DEPRECATIONS & PY3.13 MIGRATIONS",
    22: "22. PACKAGING & CONFIG HYGIENE",
    23: "23. NOTEBOOK HYGIENE",
}

# Legacy print_subheader texts that manifest cases assert, keyed by the rule
# prefix they announce (taint heredoc + SQL two-tier family).
_SUBHEADERS = {
    5: {"py.async.task-no-await": "Async error path coverage"},
    7: {
        "python.taint.": "Lightweight taint analysis",
        "py.taint.": "Lightweight taint analysis",
        "py.security.sql": "Interpolated SQL execution",
    },
}

# Rule id -> legacy print_finding title for analyzer/detector findings that
# carry their own message (SUMMARY_MAP). Pack findings embed "id: message" in
# the sink record already; pattern findings carry pattern titles.
_SUMMARY_TITLES: dict[str, str] = {
    # TAINT_SUMMARY (ubs-python.sh 173-178)
    "python.taint.xss": "Unsanitized request data reaches HTML/response sinks",
    "python.taint.sql": "User input flows into SQL execute() without parameters",
    "python.taint.command": "User input reaches subprocess/os.system",
    "python.taint.eval": "User input flows into eval/exec",
    # RESOURCE_LIFECYCLE_SUMMARY (394-399)
    "python.lifecycle.file_handle": "File handles opened without context manager/close",
    "python.lifecycle.socket_handle": "Sockets opened without matching close()",
    "python.lifecycle.popen_handle": "Popen handles not waited or terminated",
    "python.lifecycle.asyncio_task": "asyncio tasks spawned without cancellation/await",
    # ctcompare_py (GH #85 two-tier vocabulary)
    "python.ctcompare.secret_eq": "Secret, signature, or token compared with ==/!=",
    # guards_py (GH #90)
    "python.guards.deep_attr_chain": "Deep attribute chains without guards",
}


def slug_for_category(category: int) -> str:
    return _CATEGORY_SLUGS.get(category, f"cat{category}")


@dataclass(frozen=True)
class Pattern:
    """One legacy rg pipeline: a category-scoped regex with count thresholds.

    thresholds is a descending list of (min_count_exclusive, severity): the
    first entry whose count > min_count wins; when none match, the category
    reports nothing — mirroring the legacy `warning >15 / info >0` ladders.
    gate_regex expresses legacy project-wide preconditions;
    suppress_when_regex expresses count-comparison silences.
    """

    category: int
    rule_id: str
    title: str
    regex: re.Pattern[str]
    thresholds: tuple[tuple[int, str], ...]
    case_insensitive: bool = False
    exclude_regex: re.Pattern[str] | None = None  # legacy `grep -v` post-filters
    gate_regex: re.Pattern[str] | None = None  # legacy project-wide precondition
    suppress_when_regex: re.Pattern[str] | None = None  # legacy project-wide silencer


def iter_matches(pattern: Pattern, text: str) -> Iterable[tuple[int, str]]:
    """Yield (line_number, line_text) for matches, skipping excluded lines."""
    for match in pattern.regex.finditer(text):
        line_no = text.count("\n", 0, match.start()) + 1
        line_start = text.rfind("\n", 0, match.start()) + 1
        line_end = text.find("\n", match.start())
        if line_end == -1:
            line_end = len(text)
        line_text = text[line_start:line_end]
        if MARKER in line_text:
            continue  # legacy count_lines drops marker lines from counts
        if pattern.exclude_regex is not None and pattern.exclude_regex.search(line_text):
            continue
        yield line_no, line_text.strip()[:240]


def resolve_severity(pattern: Pattern, count: int) -> str | None:
    for min_count, severity in pattern.thresholds:
        if count > min_count:
            return severity
    return None


def scan_patterns(patterns: Sequence[Pattern], files: Sequence[Path], sink, skip: set[int]) -> dict[str, int]:
    """Run every pattern over the file list, writing sink records.

    Legacy parity semantics: counts are DISTINCT MATCHING LINES across the
    whole file list (rg prints each matching line once), and severity is
    resolved ONCE per pattern from that project-wide count — every record of
    a pattern carries the same severity, so summed counters equal the legacy
    print_finding buckets.

    Returns severity counters ({"critical": n, "warning": n, "info": n}).
    """
    counters = {"critical": 0, "warning": 0, "info": 0}
    active = [p for p in patterns if p.category not in skip]
    if not active:
        return counters
    texts: dict[Path, str] = {}
    for path in files:
        try:
            texts[path] = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
    for pattern in active:
        if pattern.gate_regex is not None and not any(
            pattern.gate_regex.search(text) for text in texts.values()
        ):
            continue
        if pattern.suppress_when_regex is not None and any(
            pattern.suppress_when_regex.search(text) for text in texts.values()
        ):
            continue
        hits: list[tuple[Path, int, str]] = []
        seen: set[tuple[Path, int]] = set()
        for path, text in texts.items():
            for line_no, line_text in iter_matches(pattern, text):
                key = (path, line_no)
                if key in seen:
                    continue
                seen.add(key)
                hits.append((path, line_no, line_text))
        if not hits:
            continue
        severity = resolve_severity(pattern, len(hits))
        if severity is None:
            continue
        counters[severity] = counters.get(severity, 0) + len(hits)
        for path, line_no, line_text in hits:
            sink.write(json.dumps({
                "rule": pattern.rule_id,
                "category_id": f"python.{slug_for_category(pattern.category)}",
                "path": str(path),
                "line": line_no,
                "col": 1,
                "severity": severity,
                "message": f"{pattern.title} — {line_text}",
                "suppressed": False,
            }, ensure_ascii=False) + "\n")
    return counters


def load_patterns() -> list[Pattern]:
    """Aggregate PATTERNS from every ubs_core.py_patterns.* module."""
    import importlib
    import pkgutil

    from ubs_core import py_patterns

    patterns: list[Pattern] = []
    for module_info in pkgutil.iter_modules(py_patterns.__path__):
        if module_info.name.startswith("_"):
            continue
        try:
            module = importlib.import_module(f"ubs_core.py_patterns.{module_info.name}")
        except Exception as exc:  # a broken pattern module must not kill the scan
            sys.stderr.write(f"[ubs_core.py_scan] pattern module {module_info.name} failed: {exc}\n")
            continue
        patterns.extend(getattr(module, "PATTERNS", []))
    return patterns


def _record_category(finding: dict) -> int | None:
    """Map a finding's rule id to its legacy category number."""
    rule = str(finding.get("rule", ""))
    category_id = str(finding.get("category_id", ""))
    # Registry analyzers (A2) — legacy heredocs ran inside their categories.
    if rule.startswith(("python.taint.", "python.ctcompare.", "py.taint.", "py.security.")):
        return 7
    if rule.startswith("python.lifecycle."):
        return 19
    if rule.startswith("python.guards."):
        return 1
    # category_id is authoritative for pattern/detector records.
    for num, slug in _CATEGORY_SLUGS.items():
        if category_id == f"python.{slug}":
            return num
    # Legacy `py.<slug>.<name>` ids minted after the meta-runner slug table.
    if rule.startswith("py."):
        rest = rule[3:]
        for num, slug in _CATEGORY_SLUGS.items():
            if rest.startswith(f"{slug}."):
                return num
        # Pack metadata ids (run_async_error_checks, ubs-python.sh 159-169).
        if rule == "py.async.task-no-await":
            return 5
    return None  # ast-pack rules count in totals only (legacy CURRENT_CATEGORY=0)


def run_analyzers(files: Sequence[Path], sink, skip: set[int] | None = None,
                  enable_new: bool = False) -> None:
    """Run registered python analyzers (taint, lifecycle, guards, ctcompare).

    ``python.narrowing.*`` (bead D4) has no legacy python counterpart — it
    stays off unless ``enable_new`` is set, so v2 totals match legacy.
    """
    from ubs_core import analyzers  # noqa: F401  (populate registry)
    from ubs_core.registry import analyzers_for_lang

    ctx = RunContext(lang="python", files=list(files))
    for analyzer in analyzers_for_lang("python"):
        if analyzer.layer == "narrowing" and not enable_new:
            continue
        for finding in analyzer.run(ctx):
            if skip and _record_category(finding) in skip:
                continue
            sink.write(json.dumps({
                "rule": finding.get("rule", ""),
                "category_id": finding.get("category_id", "python.security"),
                "path": finding.get("path", ""),
                "line": int(finding.get("line", 0) or 0),
                "col": int(finding.get("col", 1) or 1),
                "severity": finding.get("severity", "warning"),
                "message": finding.get("message", ""),
                "suppressed": False,
            }, ensure_ascii=False) + "\n")


def run_detectors(files: Sequence[Path], sink, skip: set[int] | None = None) -> None:
    """Run ubs_core.py_detectors.* modules (legacy heredoc detector ports).

    Protocol (single-rule modules): RULE_ID, CATEGORY, TITLE, SEVERITY,
    DESCRIPTION and ``find(files)`` yielding (path, line, col, detail).
    Multi-rule modules (e.g. the SQL two-tier detector) expose ``RULES`` —
    a tuple of (rule_id, category, title, severity, description) tuples —
    and ``find(files)`` yielding (rule_id, path, line, col, detail).
    """
    import importlib
    import pkgutil

    from ubs_core import py_detectors

    for module_info in pkgutil.iter_modules(py_detectors.__path__):
        if module_info.name.startswith("_"):
            continue
        try:
            module = importlib.import_module(f"ubs_core.py_detectors.{module_info.name}")
        except Exception as exc:  # legacy heredoc failures degraded gracefully too
            sys.stderr.write(f"[ubs_core.py_scan] detector module {module_info.name} failed: {exc}\n")
            continue
        find = getattr(module, "find", None)
        if find is None:
            continue
        if hasattr(module, "RULES"):
            specs = {
                spec[0]: {"category": int(spec[1]), "title": str(spec[2]),
                          "severity": str(spec[3]), "description": str(spec[4])}
                for spec in module.RULES
            }
        else:
            category = int(getattr(module, "CATEGORY", 7))
            rule_id = str(getattr(module, "RULE_ID", f"py.cat{category}.{module_info.name}"))
            specs = {rule_id: {
                "category": category,
                "title": str(getattr(module, "TITLE", rule_id)),
                "severity": str(getattr(module, "SEVERITY", "warning")),
                "description": str(getattr(module, "DESCRIPTION", "")),
            }}
        if skip:
            specs = {rid: spec for rid, spec in specs.items()
                     if spec["category"] not in skip}
            if not specs:
                continue
        for hit in find(files):
            if len(hit) == 5:
                rule_id, path, line_no, col, detail = hit
            else:
                path, line_no, col, detail = hit  # single-rule convenience
                rule_id = next(iter(specs))
            spec = specs.get(rule_id)
            if spec is None:
                continue
            slug = slug_for_category(spec["category"])
            title = spec["title"]
            sink.write(json.dumps({
                "rule": rule_id,
                "category_id": f"python.{slug}",
                "path": str(path),
                "line": int(line_no),
                "col": int(col),
                "severity": spec["severity"],
                "message": f"{title} — {detail}"[:300] if detail else title,
                "suppressed": False,
            }, ensure_ascii=False) + "\n")


def _finding_title(rec: dict) -> str:
    rule = rec.get("rule", "")
    if rule in _SUMMARY_TITLES:
        return _SUMMARY_TITLES[rule]
    return str(rec.get("message", rule))


def _sample_code(path: str, line_no: int) -> str:
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            for i, line in enumerate(fh, 1):
                if i == line_no:
                    return line.strip()[:200]
    except OSError:
        pass
    return ""


def _legacy_report(records: list[dict], version: str) -> dict:
    """Legacy --report-json payload (issue-64): per-rule aggregated findings
    with severity/count/title/description and up to 3 code samples."""
    by_rule: dict[str, list[dict]] = {}
    for rec in records:
        by_rule.setdefault(rec.get("rule", ""), []).append(rec)
    findings = []
    for rule, recs in by_rule.items():
        first = recs[0]
        samples = []
        for rec in recs[:3]:
            samples.append({
                "file": rec.get("path", ""),
                "line": int(rec.get("line", 0) or 0),
                "code": _sample_code(rec.get("path", ""), int(rec.get("line", 0) or 0)),
            })
        findings.append({
            "severity": first.get("severity", "info"),
            "count": len(recs),
            "title": _finding_title(first),
            "description": "",
            "samples": samples,
        })
    return {"version": version, "findings": findings}


def _render_text(args, files: Sequence[Path], counters: dict[str, int]) -> None:
    """Render the legacy-format text report from the NDJSON sink."""
    import datetime

    records = [
        json.loads(line)
        for line in Path(args.sink).read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    by_rule: dict[str, list[dict]] = {}
    for rec in records:
        by_rule.setdefault(rec["rule"], []).append(rec)

    lines = [
        f"UBS module: python (contract v2) — {args.project or args.project_dir}",
        f"Files scanned: {len(files)}",
    ]
    category_order = {num: i for i, num in enumerate(sorted(_CATEGORY_SLUGS))}
    ordered_rules = sorted(
        by_rule,
        key=lambda rule: (
            category_order.get(_record_category(by_rule[rule][0]) or 99, 99),
            rule,
        ),
    )
    current_section = None
    emitted_subheaders: set[str] = set()
    for rule in ordered_rules:
        recs = by_rule[rule]
        category_num = _record_category(recs[0])
        section = _SECTION_HEADERS.get(category_num) if category_num is not None else None
        subheader = None
        if category_num is not None:
            for prefix, text in _SUBHEADERS.get(category_num, {}).items():
                if rule.startswith(prefix) or str(recs[0].get("category_id", "")).startswith(prefix):
                    subheader = text
        if section is not None and section != current_section:
            lines.append("")
            lines.append(section)
            current_section = section
        if subheader and subheader not in emitted_subheaders:
            lines.append(subheader)
            emitted_subheaders.add(subheader)
        if section is None and current_section != "AST-GREP RULE PACK FINDINGS":
            # Legacy pack findings printed under their own header (11439)
            # and counted in totals only (CURRENT_CATEGORY=0).
            lines.append("")
            lines.append("AST-GREP RULE PACK FINDINGS")
            lines.append("ast-grep rule-pack summary")
            current_section = "AST-GREP RULE PACK FINDINGS"
        severity = recs[0]["severity"]
        title = _finding_title(recs[0])
        lines.append(f"[{severity}] {title} ({len(recs)} found) — {rule}")
        cap = 25 if rule.endswith("sql-injection") else 5
        for rec in recs[:cap]:
            lines.append(f"    {rec['path']}:{rec['line']}  {str(rec.get('message', ''))[:180]}")

    # Legacy "good" notes for emit groups whose category produced no findings.
    categories_with_records = {
        _record_category(rec) for rec in records
    }
    good_notes = {
        19: "All tracked resource acquisitions have matching cleanups",
        5: "All async operations appear protected",
        4: "No 'is' literal comparisons",
    }
    for num, note in good_notes.items():
        if num not in categories_with_records and num not in _skip_set(args):
            lines.append(f"good: {note}")

    lines += [
        f"Critical issues: {counters['critical']}",
        f"Warning issues: {counters['warning']}",
        f"Info items: {counters['info']}",
        f"Report generated: {datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}",
    ]
    Path(args.text_out).write_text("\n".join(lines) + "\n", encoding="utf-8")


def _skip_set(args) -> set[int]:
    return {int(part) for part in (args.skip or "").split(",") if part.strip().isdigit()}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python3 -m ubs_core.py_scan")
    parser.add_argument("--files-from", default="-", help="NUL-separated file list ('-' = stdin)")
    parser.add_argument("--sink", required=True, help="NDJSON findings sink path")
    parser.add_argument("--project-dir", default="", help="base dir for relative sink paths")
    parser.add_argument("--skip", default="", help="comma-separated category numbers to skip")
    parser.add_argument("--ast-rule-dir", default="", help="consolidated ast-grep rule dir (sgconfig-*.yml + manifest.json)")
    parser.add_argument("--text-out", default="", help="write the legacy-format text report here")
    parser.add_argument("--json-out", default="", help="write the UBS summary JSON document here")
    parser.add_argument("--project", default="", help="project path recorded in the json summary")
    parser.add_argument("--version", default="", help="module version recorded in the json summary")
    parser.add_argument("--fail-on-warning", action="store_true")
    parser.add_argument("--enable-new-analyzers", action="store_true",
                        help="run analyzers with no legacy counterpart (python.narrowing)")
    args = parser.parse_args(argv)

    if args.files_from in ("-", ""):
        data = sys.stdin.buffer.read()
    else:
        data = Path(args.files_from).read_bytes()
    entries = data.split(b"\0") if b"\0" in data else data.splitlines()
    files = [Path(raw.decode("utf-8", "surrogateescape")) for raw in entries if raw.strip()]
    skip = _skip_set(args)

    patterns = load_patterns()
    with open(args.sink, "w", encoding="utf-8") as sink:
        counters = scan_patterns(patterns, files, sink, skip)
        run_detectors(files, sink, skip)
        run_analyzers(files, sink, skip, enable_new=args.enable_new_analyzers)
        if args.ast_rule_dir:
            from ubs_core.py_ast import scan_all
            from ubs_core.py_rules import CATEGORY_MAP, SEVERITY_MAP

            # Legacy calibration: the rule pack counts EVERY rule bucket
            # (run_ast_rules text mode), independent of --skip; only the
            # run_async_error_checks rule is category-gated (cat 5).
            # Severity: YAML/manifest map wins; ASYNC_ERROR stays warning.
            overrides: dict[str, str] = dict(SEVERITY_MAP)
            manifest_path = Path(args.ast_rule_dir) / "manifest.json"
            if manifest_path.is_file():
                try:
                    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
                    for rid, meta in manifest.items():
                        if isinstance(meta, dict) and meta.get("severity") and rid not in overrides:
                            overrides[rid] = meta["severity"]
                except (ValueError, OSError):
                    pass
            ast_counters = scan_all(
                Path(args.ast_rule_dir), files, sink, overrides,
                count_only=None, skip_categories=None, category_map=CATEGORY_MAP,
                skip=skip,
            )
            for key, value in ast_counters.items():
                counters[key] = counters.get(key, 0) + value

    # The sink is the single source of truth: recount severities from it so
    # every layer (patterns, detectors, analyzers, ast) is reflected in totals.
    counters = {"critical": 0, "warning": 0, "info": 0}
    for line in Path(args.sink).read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        try:
            severity = json.loads(line).get("severity", "info")
        except ValueError:
            continue
        counters[severity] = counters.get(severity, 0) + 1

    exit_code = 1 if counters["critical"] else 0
    if args.fail_on_warning and (counters["critical"] + counters["warning"]) > 0:
        exit_code = 1

    if args.json_out:
        records = [json.loads(line) for line in Path(args.sink).read_text(encoding="utf-8").splitlines() if line.strip()]
        import datetime

        legacy_findings = _legacy_report(records, args.version)["findings"]
        doc = {
            "language": "python",
            "project": args.project or args.project_dir,
            "timestamp": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "files": len(files),
            "critical": counters["critical"],
            "warning": counters["warning"],
            "info": counters["info"],
            "version": args.version,
            "status": "ok",
            "findings": legacy_findings,
            # Legacy issue-64 payload (title + samples) carried inside the
            # module summary so the combined JSON keeps per-finding samples.
            "report": {"version": args.version, "findings": legacy_findings},
        }
        Path(args.json_out).write_text(json.dumps(doc, ensure_ascii=False) + "\n", encoding="utf-8")

    if args.text_out:
        _render_text(args, files, counters)

    sys.stderr.write(json.dumps({"counters": counters, "patterns": len(patterns)}) + "\n")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
