"""A library module that prints instead of logging is still reported.

Companion to debug_print_cli_clean.py: no shebang, no __main__ guard, no
argument parser, no sys.argv — nothing here declares a CLI role, so the
category-11 ladder must still reach its warning tier.
"""


def emit(rows):
    print("row 0")
    print("row 1")
    print("row 2")
    print("row 3")
    print("row 4")
    print("row 5")
    print("row 6")
    print("row 7")
    print("row 8")
    print("row 9")
    print("row 10")
    print("row 11")
    print("row 12")
    print("row 13")
    print("row 14")
    print("row 15")
    print("row 16")
    print("row 17")
    print("row 18")
    print("row 19")
    print("row 20")
    print("row 21")
    print("row 22")
    print("row 23")
    print("row 24")
    print("row 25")
    print("row 26")
    print("row 27")
    print("row 28")
    print("row 29")
    print("row 30")
    print("row 31")
    print("row 32")
    print("row 33")
    print("row 34")
    print("row 35")
    print("row 36")
    print("row 37")
    print("row 38")
    print("row 39")
    print("row 40")
    print("row 41")
    print("row 42")
    print("row 43")
    print("row 44")
    print("row 45")
    print("row 46")
    print("row 47")
    print("row 48")
    print("row 49")
    print("row 50")
    print("row 51")
    print("row 52")
    print("row 53")
    print("row 54")
    return len(list(rows))
