#!/usr/bin/env bash
# Shared primitives for the UBS language modules (bead A1, library v1).
#
# Sourced by every modules/ubs-<lang>.sh:
#   UBS_MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
#   source "$UBS_MODULE_DIR/lib/ubs-common.sh"
#
# Distributed and checksum-verified exactly like the helpers (HELPER_ASSETS /
# HELPER_CHECKSUMS in the meta-runner, key "lib/ubs-common.sh"), so a cached
# module always finds the library next to itself.
#
# Everything here used to exist in 4–7 drifted copies across the modules; the
# bugs those copies carried (LC_ALL assigned but never exported, json_escape
# bodies that break under `set -u` or skip control characters, silent text
# fallback for --format=toon/jsonl) are fixed once, here.

if [[ -n "${UBS_COMMON_LOADED:-}" ]]; then
  return 0 2>/dev/null || exit 0
fi
UBS_COMMON_LOADED=1
# Read by the modules and quality/test_ubs_common.py after sourcing.
# shellcheck disable=SC2034
UBS_COMMON_VERSION="1"

# ── Locale ──────────────────────────────────────────────────────────────────
# Child tools (sort, grep, awk, rg) must see the C locale for byte-stable
# ordering and matching; Python helpers keep UTF-8 I/O regardless.
ubs_export_locale(){
  export LC_ALL=C
  export LANG=C
  export PYTHONIOENCODING=utf-8
  export PYTHONUTF8=1
}

# ── Time / failure ──────────────────────────────────────────────────────────
ubs_now_ms(){
  if [[ -n "${EPOCHREALTIME:-}" ]]; then
    local s="${EPOCHREALTIME%.*}" us="${EPOCHREALTIME#*.}"
    printf '%s\n' $(( s * 1000 + 10#${us:0:3} ))
  else
    local ns; ns="$(date +%s%N 2>/dev/null || echo 0)"
    printf '%s\n' $(( ns / 1000000 ))
  fi
}

# ubs_die MESSAGE [EXIT_CODE=2]: environment/usage errors exit 2 by contract.
ubs_die(){
  printf '✗ %s\n' "$1" >&2
  exit "${2:-2}"
}

# ubs_with_timeout SECONDS CMD...: run CMD under `timeout` when available
# (0 = no limit); exit status is the command's, or 124 on timeout.
ubs_with_timeout(){
  local secs="$1"; shift
  if [[ "$secs" =~ ^[0-9]+$ && "$secs" -gt 0 ]] && command -v timeout >/dev/null 2>&1; then
    timeout "$secs" "$@"
  else
    "$@"
  fi
}

# ── Asset integrity & helper resolution (bead E1) ────────────────────────────
# ubs_sha256_file FILE: compute sha256 digest of FILE (prints hex string).
# Returns 0 on success, 1 on missing file or unavailable hash tool.
ubs_sha256_file(){
  local file="$1"
  [[ -f "$file" ]] || return 1
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$file" 2>/dev/null | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$file" 2>/dev/null | awk '{print $1}'
  elif command -v openssl >/dev/null 2>&1; then
    openssl dgst -sha256 "$file" 2>/dev/null | awk '{print $NF}'
  else
    return 1
  fi
}

# Pinned helper and asset checksums for standalone module execution (bead E1).
# Auto-generated by scripts/update_checksums.py.
if ! declare -p UBS_HELPER_CHECKSUMS >/dev/null 2>&1; then
  declare -g -A UBS_HELPER_CHECKSUMS=()
fi
declare -g -A UBS_COMMON_HELPER_CHECKSUMS=(
  ['helpers/async_task_handles_csharp.py']='d5b029f8fe9452fafba22a9bd6a26db9952b8072fdee224d976f140c824af93d'
  ['helpers/cfg_test_only_modules_rust.py']='27dbd7f843d546c07743bf642f4dfa9912f0c205007c583c5e18d6b52fa39e68'
  ['helpers/resource_lifecycle_cpp.py']='886611236e8230551ad302bc2b91894935adb29f427dff92c5e0e18370e9f582'
  ['helpers/resource_lifecycle_csharp.py']='e268a5472ddbf3039186ce640c0d5c816727c9599dd644cab08ad53c19962426'
  ['helpers/resource_lifecycle_go.go']='53d441968ed81b7947adde9838d0cc09d04effa84784d33e52bcdd60a78eec0d'
  ['helpers/resource_lifecycle_java.py']='99ee1a5d4cf28ec0ad4907308fe494cb71501957e17cae056a36095783db1892'
  ['helpers/resource_lifecycle_py.py']='f736488bdd243fa0b142dc07193d43739bd69f819e5276eeaa81e6c7cb5e6813'
  ['helpers/resource_lifecycle_ruby.py']='9756c313b2718337cf3ac35aadc29e5bf0077f4474c8c01e01a7de0bf864b185'
  ['helpers/resource_lifecycle_swift.py']='c88e2611d532915bc59c7169d70c7b1585fdfdb7127ca5eda5214310821bbc9d'
  ['helpers/type_narrowing_csharp.py']='58fc5048b3851664876859a16e807600b0ec5c2300bdefed39d674f9b07b1ee1'
  ['helpers/type_narrowing_kotlin.py']='a50e5060d1784b53e27cfc4dba745011fb2e3b7bd15176f91f0477eced54d321'
  ['helpers/type_narrowing_rust.py']='155095a92a5a90ef88d668a88236f7d8611ec6f94aad42615eacdbe92b21e163'
  ['helpers/type_narrowing_swift.py']='d83d064db4418d4c245e6bcf7a386280e27c0ebdc57a7c4f6c32443887d6eeea'
  ['helpers/type_narrowing_ts.js']='37cefad3c650ae04d1c5f7da42edfca3b5dea1f0c2263025bcec527111b930c9'
  ['helpers/ubs_core/__init__.py']='da56f2c0f546857877f7fec9854146ece87cb543b1b368efd4fd88986bf47bde'
  ['helpers/ubs_core/__main__.py']='4aed5b835f04ba3a51b13a650b15dc05e2e43436e9e8be19000551999172639e'
  ['helpers/ubs_core/analyzers/__init__.py']='090badfe6b8be4c60de495a74b362acff5a4d9f8461dbb56d5b6718783e39b86'
  ['helpers/ubs_core/analyzers/async_event_emitter.py']='eaa22abf72e33569b102b9b6425082e409f8191b8e4e0dc30a16c64d3e5edbfd'
  ['helpers/ubs_core/analyzers/async_event_listener.py']='fe7c29dd3d98efdb88bb7c07176598e9f496c21fbee69d9c41049058bf83fa1b'
  ['helpers/ubs_core/analyzers/async_flatmap.py']='4b2c989d6962906166950f3f9590b2359e55096160b0fe82bda77aeee7d6a5d3'
  ['helpers/ubs_core/analyzers/async_foreach.py']='cc474803af4d727ce22c8f8b59b72111879324714cd774f7068e37bc65f39c43'
  ['helpers/ubs_core/analyzers/async_handles_csharp.py']='830d3853356dd3f631bc3ec2b949dc51f46ac8e71cb812948713bede783c898a'
  ['helpers/ubs_core/analyzers/async_jsx_handler.py']='e1bd2c9e970304c43caabbad44271319e9769873e3ae032bb6de657302bcfc20'
  ['helpers/ubs_core/analyzers/async_map_awaited.py']='8b11c366f5aca6f293c3fef48d7ec96ac830424c86f714acc60c9f3eee09aa4e'
  ['helpers/ubs_core/analyzers/async_map_ignored.py']='70b8babeb147c0d4d81a8128dbb1c4d5af6723f29cc182d61cd9a8a1f0131032'
  ['helpers/ubs_core/analyzers/async_predicates.py']='8a68cfcc012b6220e5472222979537f0c6016874de0cd6c72ee626ffdc907628'
  ['helpers/ubs_core/analyzers/async_promise_all_foreach.py']='bc2e00a5781a8ea5c395c1249f9404cc00b38119ea70bc21e1e7fc4f7395c008'
  ['helpers/ubs_core/analyzers/async_promise_all_map.py']='da1f6024e29eba09b84536d9d5046ae9b627b24d67027d89382915b19393e5c8'
  ['helpers/ubs_core/analyzers/async_promise_executor.py']='093cbd0bc705b696e8a222e9bc9307ab450e5fb180276cd73f835a6e79dece4a'
  ['helpers/ubs_core/analyzers/async_react_effect.py']='9611185bed87c651dded2ba12e484245c202dc87c7c73ed7bdbb7408dd5da0ba'
  ['helpers/ubs_core/analyzers/async_reduce.py']='6cd736c100dfaf1871c15734e46ecec3972eb0e36c5ece7b67ecef807c2b0ccc'
  ['helpers/ubs_core/analyzers/async_sort_comparator.py']='7410aaa138a3a9204a0e47fc81ed9942f14031728edd21a991373df5d17c225b'
  ['helpers/ubs_core/analyzers/async_timer.py']='b24c3462cfc469c330ecfc63ff63e2d20cc2b92165f627dc148ac76bbf105ea4'
  ['helpers/ubs_core/analyzers/cfg_test_only_rust.py']='5269b88dd078cae71d1a3c2e23523032507ac49265560dd0c27273c41c38c5aa'
  ['helpers/ubs_core/analyzers/ctcompare_go.py']='67b66f44a697628c36dc5499aa40e9bfd737391d72f6940a623ef427d7a4e64d'
  ['helpers/ubs_core/analyzers/ctcompare_js.py']='43695373ce47cbe3ff6810d3f1dfdb748d8a104247415ba214d3bee9c225135a'
  ['helpers/ubs_core/analyzers/ctcompare_py.py']='9b340f59fddbb1fd1b5220174ddee79944797179a09bc01a7262a1d7c8d1a2dc'
  ['helpers/ubs_core/analyzers/ctcompare_rust.py']='09f5d6a096a1cd16d0c05b1536a53db14a422a7e3399d6050df1c6646e691b35'
  ['helpers/ubs_core/analyzers/guards_generic.py']='61ef81e6255aa3c09ed175648f8cbd99ee2bff9a98ed3c968781533beb91b4a5'
  ['helpers/ubs_core/analyzers/guards_js.py']='4a27ccb62965a474c40de644f15cf2e4018642f42971501c480d7015c399eafa'
  ['helpers/ubs_core/analyzers/guards_py.py']='59b4edae6b864cff5e8f93315765b3011b8fef4a8a3c0dfd0aa871fe879d2329'
  ['helpers/ubs_core/analyzers/guards_ruby.py']='aed0e66449bd1b3a36f69eafdd8b9fac966c9b2eb2c11ff355da01ec64a5f61b'
  ['helpers/ubs_core/analyzers/lifecycle_cpp.py']='245804579718f5c4beb3bb7e3522a628e7338d41127ca03febfdbaad064bb55b'
  ['helpers/ubs_core/analyzers/lifecycle_csharp.py']='e1c18d5e427645eba8a2628853fb8fc6ca6d6259ec3d49cfc44907ce9e1b150a'
  ['helpers/ubs_core/analyzers/lifecycle_java.py']='5b1d60fbe75a0b3f1ae25cc2c11210e5899ddbca0afd4047e3624789b561ebe2'
  ['helpers/ubs_core/analyzers/lifecycle_py.py']='84b4fb6371c00d9b787e26feeface5cd1fd99c142d9ad840f96d81ce33647c15'
  ['helpers/ubs_core/analyzers/lifecycle_ruby.py']='b5d928e4dc9f504c3c427f51463e5ad6bfe69f86e9cc6f591ca8757d5ce053cd'
  ['helpers/ubs_core/analyzers/lifecycle_swift.py']='51b065554c6b5310ad66f0fd862f113d81cb6822faf23f57215cbf953e0b2c34'
  ['helpers/ubs_core/analyzers/narrowing_cpp.py']='5681c018729ec37129d808d9f65ec51e368c060e0b0ce4d363b461afcd4d9345'
  ['helpers/ubs_core/analyzers/narrowing_csharp.py']='436ce2e1f5a5e1384915b54d67fcfaae7156d607331bbaa1f27680610a6ccd17'
  ['helpers/ubs_core/analyzers/narrowing_elixir.py']='40af9808f556825b6ce81397c37d5ed5100ce34cbf2a7ea291be4c7f280ff7ee'
  ['helpers/ubs_core/analyzers/narrowing_go.py']='123895581adf37f5670b8e8f3b21bc2bf75f3495e82077a80039718324be5771'
  ['helpers/ubs_core/analyzers/narrowing_kotlin.py']='d84c7099d32ccefbef2bdc253b3473ccbfa2f4532f55139ebff46de01c81ee5e'
  ['helpers/ubs_core/analyzers/narrowing_py.py']='60a2381463f1e7e8ff66e9a6a8564baa2aff1d10c2f107e3d24b23a4341bde9a'
  ['helpers/ubs_core/analyzers/narrowing_ruby.py']='4af90a09f6336c242dd5eb58efec6df8ab12a0a3dbe2e282a34e55d7723d2555'
  ['helpers/ubs_core/analyzers/narrowing_rust.py']='54ec29f4297cbe37aec4cdaab276a6880bb16fd93377ed060e90c5de98261b12'
  ['helpers/ubs_core/analyzers/narrowing_swift.py']='2a7971f6f6a858eb73d1f898a6fdd039a56be405222877eae3890a6343a52a73'
  ['helpers/ubs_core/analyzers/regex_swift.py']='236c0fc8aca7c8c2d6b3270bfcc14f16e81a7caf95e500adc9ac176b33490311'
  ['helpers/ubs_core/analyzers/sec_archive_entry.py']='8e0fa1e0894e22ab9577fd38495243304937ee12a415fec4612799762ea10812'
  ['helpers/ubs_core/analyzers/sec_cookies.py']='51159ac937df932c0a4f85f7a821fda2176af57f67d444a39eaf6a720dff3462'
  ['helpers/ubs_core/analyzers/sec_cors.py']='9829cdaaa0f7e03e6dcbf2919dfe7810b32cc63dcbfa23250c721841aea23705'
  ['helpers/ubs_core/analyzers/sec_dangerous_html.py']='a236bdc0a4c31c526d3145ec2a23349eda8d4583dd9fa8f28d90d6e0e11e129c'
  ['helpers/ubs_core/analyzers/sec_fetch_abort.py']='c97160ab7268b66914622d5add6e01f556c9753669dda5e4da20f120a3aa9067'
  ['helpers/ubs_core/analyzers/sec_hardcoded_secrets.py']='9564e2f6c67689bb70634ded9591729ad849a3b027cf6f4c50133484d4e521af'
  ['helpers/ubs_core/analyzers/sec_header_injection.py']='3229fdd4b240227aea161666cd7e1b49f5b045f1fb372378e45cbfb19e4c187d'
  ['helpers/ubs_core/analyzers/sec_host_header.py']='82019d4465d304ff49aaf7166be4008a79ff77cdaeb0ff3ae3afc3cc3d5c58b5'
  ['helpers/ubs_core/analyzers/sec_jsx_target_blank.py']='faa862aed990d876d69bf3c2684c5d5f6698aed592559f5a630e9332ebb40418'
  ['helpers/ubs_core/analyzers/sec_jwt.py']='7d4a32a0907a51960514de51d39f7014976c8c7b7664e6b2936bbb43ee971497'
  ['helpers/ubs_core/analyzers/sec_message_origin.py']='8cd0fd1b4babd400a5e095f83161713b0011c2357f5978f7896b6a2e1e061a53'
  ['helpers/ubs_core/analyzers/sec_open_redirect.py']='f9c24bdfc5731257c3e4bfeede9afc540552c105d3a49e654327f33513a7ee52'
  ['helpers/ubs_core/analyzers/sec_path_traversal.py']='3d775e3a4cff45874ece82913e7249ec454f69a51e5bbd0b136474b713f8a2b1'
  ['helpers/ubs_core/analyzers/sec_post_message.py']='b145ea65ec6bf61e7ac061ae4dce7d408602bfc8b6d80d9caabb35b9e3ed0e04'
  ['helpers/ubs_core/analyzers/sec_prototype_pollution.py']='cddb919040be5c1e49c5817e1764b0e7d9010518780f7a641d59ced199184260'
  ['helpers/ubs_core/analyzers/sec_request_body.py']='3c0388262e84a97efa6524e0092045aa274f3f50d55d9302fe285e3acd4c57bd'
  ['helpers/ubs_core/analyzers/sec_request_regex.py']='e1864b9516b1bca67fe8ba1c905483edbb6bba39ed1eaba29a0332e4afd73107'
  ['helpers/ubs_core/analyzers/sec_reverse_proxy.py']='76bea3c83e8ce84f0d6e74458073ee0a12fc46c4e5b3d1dd03bb8f3155de9a6f'
  ['helpers/ubs_core/analyzers/sec_sql_injection.py']='aa570ba4bdbca3811912a33bc9b7f1a5bb329a69ace3b00b93ddf5a9de0fe21e'
  ['helpers/ubs_core/analyzers/sec_ssrf_fetch.py']='e3129ff62a7409b48a76e21bef14d1369a235ace660c7f4aff2bce150db30a56'
  ['helpers/ubs_core/analyzers/sec_tls.py']='73a05b375432deb7870cc5f49de93a0adc4a60ad3f4abe1cb2741d94ba5415b6'
  ['helpers/ubs_core/analyzers/sec_weak_random.py']='46a83ae8945231794c6bceb3f716f91590db4e8498659b9fddf997eb6f3721e4'
  ['helpers/ubs_core/analyzers/spec_block_function.py']='e6f7c50f8a3d5e32d5b2d8bfbf7b58f47662bb64269030916436a9d8e476d569'
  ['helpers/ubs_core/analyzers/spec_division.py']='996882aa746453f22136f358b845c9879db8a4d44c40562c91cb472c09df9d42'
  ['helpers/ubs_core/analyzers/spec_hooks.py']='15b16283c790e7221470d8590980f9ef5d5b094ab9724dc1f0ef78c8ab9a28db'
  ['helpers/ubs_core/analyzers/spec_switch_fallthrough.py']='00eec5eb639e7f17897ca4f2e01c1ba62ceda8fc76d3587b6c9ee1d4aa287d7b'
  ['helpers/ubs_core/analyzers/spec_typeof.py']='0906435deed901a406424bd975229a09f062d86dbc7d597adff2ddc9b2b1cce6'
  ['helpers/ubs_core/analyzers/taint_cpp_redirect.py']='a0aa2b41717cc34a42584f2bb41c98cae4a8ca8a278727bde536dfe9ab91b386'
  ['helpers/ubs_core/analyzers/taint_cpp_traversal.py']='a227b9036b5e349c320ace0f0bafbc485e1a373bf24c2ee23faaf078bb1dfefc'
  ['helpers/ubs_core/analyzers/taint_csharp_redirect.py']='fc8cfe379e8748b2205b6abacfd4128c9940898f1e105ab51d5d953b8e2b819d'
  ['helpers/ubs_core/analyzers/taint_csharp_request.py']='8f7417712afe5399d18918b2b4ddb2f46ac4120ee53dabb2c0cf29f03806ee61'
  ['helpers/ubs_core/analyzers/taint_elixir_redirect.py']='202e2caccea68799411b7e5952df2f56ebc16304e62acb6257c73ae53d4ced6a'
  ['helpers/ubs_core/analyzers/taint_elixir_traversal.py']='101708e33c995cab0500d02bee67814937e29088244f992aa231f1d209677320'
  ['helpers/ubs_core/analyzers/taint_go.py']='db62a04ce159027c6fab2941fc481b7b986faefa3996a124d22c56c0b9dfa1a7'
  ['helpers/ubs_core/analyzers/taint_java_redirect.py']='39fb0763494056f30a450f8c9296b02effc9a18a06d6560b8beeefa67310dc90'
  ['helpers/ubs_core/analyzers/taint_java_traversal.py']='c73cbe618a30944ca491dac09aa667f3e2599b1c54f95a8a9747bdad9135dcfd'
  ['helpers/ubs_core/analyzers/taint_js.py']='c8488a2b33b0388e44617e0d990e8cdaca1543a779238aa22f4043a7d54a84b0'
  ['helpers/ubs_core/analyzers/taint_py.py']='c500fea0fdb89d73c5c35c6d26a8bc3916575a25c4f51f012c32d506547370e7'
  ['helpers/ubs_core/analyzers/taint_ruby_traversal.py']='ecff0b7c2607695048741f48551209464e80db385415490d1ebd92227a9813e0'
  ['helpers/ubs_core/analyzers/taint_ruby_url.py']='4453f0434f95879880777748ab7d6041fa81588bf281c9ec9a2183c2cc706c63'
  ['helpers/ubs_core/analyzers/taint_rust.py']='d7b70068d53f76e78f3bdded9a6eda734987c6e2de59ea9739682ca99deb30fa'
  ['helpers/ubs_core/analyzers/taint_swift_redirect.py']='467563f6db08bc1045679d2c406e9eab3f824c7770cbf83c2756f4135b08b45d'
  ['helpers/ubs_core/analyzers/taint_swift_traversal.py']='98c81269a30a7fc2aa2666cfce499048e7ece01880873e53c2c5b9ca819a66e0'
  ['helpers/ubs_core/bash_rules.py']='b61a431da8298cb7c59e6c2858943536bb1e6308a289ee27698b119fdd7dc5f3'
  ['helpers/ubs_core/bash_scan.py']='2148f5d132083fe6ac928d3e6f21b61a2a24f48131d032d4060a0e6bc22c11d0'
  ['helpers/ubs_core/cache.py']='5218c45e221efb5c92e6427921172c106afec22372a2c61bf85741cf9bb1f15b'
  ['helpers/ubs_core/cli.py']='7b7b8ca7ac8477b26917a9e184a9d48a300a9c4a9a478b64e1ca38b1c530f3f3'
  ['helpers/ubs_core/cpp_detectors/__init__.py']='b74840d5af31f44ac13703f3c66f6968af4207c9ce08f3c0ae1010cd62c4fabd'
  ['helpers/ubs_core/cpp_detectors/archive_entry.py']='60f203857d374aa48f68180d829894d9561bad3b7535f72c22246ebc297ad86e'
  ['helpers/ubs_core/cpp_detectors/async_errors.py']='ba135d496604b1822a30b8e2942b5a3700884c4d2d11409b9c4bddf1763f1d13'
  ['helpers/ubs_core/cpp_detectors/header_hygiene.py']='9e4a9256776e416083dadc3ff25f6af59da08b0584a7ec290fba4b0ce68e606b'
  ['helpers/ubs_core/cpp_detectors/header_injection.py']='474ee4a35e6789fba277fb64456648dfac257320cdd3eb295b49ce4614731403'
  ['helpers/ubs_core/cpp_detectors/outbound_url.py']='18062173d093d8b040cc9faed3c2d302e59565feae16c6191293dd46cb67c149'
  ['helpers/ubs_core/cpp_detectors/perf_io.py']='ce1652f1df907eef5045dd3bf7fce90e1cc9b914d34a8ad1297c19b14827b26e'
  ['helpers/ubs_core/cpp_detectors/quality_markers.py']='576cc873818cd5c4a5c5492715486adc90f20a91b2d3f1cdb59f73e5730e0a24'
  ['helpers/ubs_core/cpp_detectors/weak_random.py']='8f6a7b8181d820134a6180f41648ff52db39db78170ed6f95a9504bb9fa0d594'
  ['helpers/ubs_core/cpp_patterns/__init__.py']='e2837237df1ae19ebac33c1ad27943315d86d0986972909cc79830b7cf11b94c'
  ['helpers/ubs_core/cpp_patterns/concurrency.py']='8a46b04930ab6a9185807f48071a6cfddf18ffb5a41dd593c3f635e8c7c08243'
  ['helpers/ubs_core/cpp_patterns/debug.py']='4ec4eb9b8b27d6bfd32c91290cd65470d5ad9c7bbd3b466d2816ba706deb50f4'
  ['helpers/ubs_core/cpp_patterns/exceptions.py']='827703aad5a34a8fb9cbddc01a6284a96f7f8369f87cfe4259f1cff43bec7884'
  ['helpers/ubs_core/cpp_patterns/headers_stl_io.py']='cf774ff009fc2c22b66c14be52955b652f5d24cfcd8e9bfff64ff90e25499b9c'
  ['helpers/ubs_core/cpp_patterns/macros_cmake.py']='aad071a77c7f4a27387d06acc7d62880e0b4de8bf4c28d0f84d46a08e61dc500'
  ['helpers/ubs_core/cpp_patterns/memory_raii.py']='ec6bc9af91847e7c059b04cbcfd4a0298577c9a043ad63b220ce82b5a4302be7'
  ['helpers/ubs_core/cpp_patterns/modernization_pointer.py']='5d01f475b034b26e4d193c8b176f51b9cd5de8df0a874dee8f59b7751a74ab06'
  ['helpers/ubs_core/cpp_patterns/numeric.py']='fc04ecf9b703ab8f5aadd435fa5a137c7541028b1c92e74b6d2dc5448fb58444'
  ['helpers/ubs_core/cpp_patterns/ub_zone.py']='61b92efa13a0c9876ef657d9e56c600ef15f8e3486ad0b64ff4f4ad4c26327aa'
  ['helpers/ubs_core/cpp_scan.py']='bbfcbdc88a5c8802233e07ab5a8ae88a9a3b6d8b7ff305db66670787dac10e30'
  ['helpers/ubs_core/csharp_ast.py']='073e21aa2a80a68fe0c7afd2fc5f8b8ba8503f5cc0f9844e0b26c4ca18e8754e'
  ['helpers/ubs_core/csharp_detectors/__init__.py']='bf8a8383f6143a5e585e78fec84580e86c40ee180f05a7bbce386c496d420063'
  ['helpers/ubs_core/csharp_detectors/_common.py']='5f4fba0b6efd3d158ebcce7179b0c56eda3c4eb453dab255443e538496d3ba56'
  ['helpers/ubs_core/csharp_detectors/archive_extraction.py']='a231403de45648699d14169d97a12eb671551ee4dada8de30fcb5c3d8525793f'
  ['helpers/ubs_core/csharp_detectors/header_injection.py']='e10c395578d049851c135d999ee1b2262df6755db99c991a8048730ecac1afe9'
  ['helpers/ubs_core/csharp_detectors/outbound_url.py']='964ed09a07bbc5a00034c975086da7ec1315fc61267ff1bb4a1b26eb8440f64e'
  ['helpers/ubs_core/csharp_detectors/security_randomness.py']='78994390f1093bc36f0dd070ecccf7f4c366f866ecada0a0107b50c682c147a5'
  ['helpers/ubs_core/csharp_patterns/__init__.py']='1dfc28708bd9a28b904a2665f0532439f4b83c6ef3a16ea8cbdfa2083240bc57'
  ['helpers/ubs_core/csharp_patterns/_table.py']='bb656efe1ad9c4546ebcafefd23128e1e3f14f4ef9fe1f60e9491ffe2c516ef1'
  ['helpers/ubs_core/csharp_patterns/async_locks.py']='e5e8bd55f6ba99af0db0fb4ae2cc111e2d93094fa83bb27a3934511c474da400'
  ['helpers/ubs_core/csharp_patterns/concurrency.py']='de4834bc244b0337d3428554ff2613eb297657ae2ebc55659095afb138934f71'
  ['helpers/ubs_core/csharp_patterns/correctness.py']='927a55db74451ee875d9db082d6cfb2caafc9587e7e60685a7eeae6d8772a9c7'
  ['helpers/ubs_core/csharp_patterns/foundations.py']='9c581ac68509fe2f8f708788d80bb38f1b24266350fa30eb3b48d27a09b6cb9f'
  ['helpers/ubs_core/csharp_patterns/quality.py']='eac32fcf8ce9ce593f19c2089abf89916b72cbd6ea1005ac056d23a178bb69cc'
  ['helpers/ubs_core/csharp_patterns/security_rg.py']='456a7b2ad7855b36376dfa8daa34c1d6449eb7b07d86a2b5b654180307665ec1'
  ['helpers/ubs_core/csharp_rules.py']='9a528e9ea14daae283420bb82854dc06d32cc1588f87af8b1819503dfeb7bd68'
  ['helpers/ubs_core/csharp_scan.py']='b35c20676394cc683abf1bd66d496c64bfd76409101bbfe9ede65085f3d014c7'
  ['helpers/ubs_core/elixir_detectors/__init__.py']='9e08cda01f060bb0e804ad7276b680e12f8f7451158b2ba443bc001d2f086faa'
  ['helpers/ubs_core/elixir_detectors/_common.py']='ffedf7e7db651bb0738e999fa2cb6f175cd97b52fa3bc857a809be54ac887eee'
  ['helpers/ubs_core/elixir_detectors/archive_extraction.py']='90acf3bc6a1c96577ae43f10309326e67699b18475011fec01cda4d49529a9ea'
  ['helpers/ubs_core/elixir_detectors/config_runtime_exs.py']='015a6946ce0ae56280e14bcbbdc756a78f1aca1cd3410193dd84edfd7b48dcb1'
  ['helpers/ubs_core/elixir_detectors/hardcoded_secrets.py']='be97a18a6bfd572b9f0c0e6a031331be0ccdc85c06409dedd09a8c67b8fd698f'
  ['helpers/ubs_core/elixir_detectors/mix_lockfile.py']='68fda905182218603ad78cfa65910d9b219cc9bcea34c8fadd6c1a749106b5ed'
  ['helpers/ubs_core/elixir_detectors/outbound_url.py']='851158fd493d2a7a60a64bc8242fb58e069d538b21f28a7f4c06d36254e44dbe'
  ['helpers/ubs_core/elixir_detectors/response_header_injection.py']='4de3985f930862239fdacecef0854c76514926d2a1d7e90b659c0b72a25ac3d6'
  ['helpers/ubs_core/elixir_detectors/security_randomness.py']='8826d5378ba5c50de0ab8b392da8dbfe29197e43843cf76072e5562bfe424a93'
  ['helpers/ubs_core/elixir_patterns/__init__.py']='7148f31ca91d7ec307a64dbcc99bb9ee241580143719b48c05aba2fa53ef8641'
  ['helpers/ubs_core/elixir_patterns/debug_quality.py']='a1c59c62bf985511f25388c83d8e2d69fd0cb9dfdc49931a93a972e556553c9e'
  ['helpers/ubs_core/elixir_patterns/ecto_concurrency.py']='5b62edda642fde35481d24c9fbe1e3af10bf4892019eb68be8d88f7f2970e410'
  ['helpers/ubs_core/elixir_patterns/foundations.py']='5d82afa7c982924d3df36a1702158dc4e59ff7721ad396826fbb60dab6d02c66'
  ['helpers/ubs_core/elixir_patterns/mix_deps.py']='bbf8f009f9d25873c918e9fcb4b23b185d9f9a7e467bd36d1638a53576d42127'
  ['helpers/ubs_core/elixir_patterns/perf_misc.py']='5248f2e9c2b845736a9d95cf301d791f474f1d82fd063f170c4c702f54960f7a'
  ['helpers/ubs_core/elixir_patterns/phoenix.py']='533afcfc1a90e24ad2ce002a76d2433ef2203f7034de9047a84c7a67eb0f36a4'
  ['helpers/ubs_core/elixir_patterns/security_rg.py']='551c5357954168766253ec46bf2095b7497d500c01d2a71fbbb77849461c51c9'
  ['helpers/ubs_core/elixir_scan.py']='2da832a8ab741aa9eab6672ec43d9986f2eff05ff212a0f78da145879e2f9164'
  ['helpers/ubs_core/explain.py']='c2c440b5ef72c8f5cc87342d3ed6f8eee530bdf71eb425e7f4f771b4df4dc6ba'
  ['helpers/ubs_core/findings_merge.py']='4a0ebf880587dedc209da93c7155f0c29d73566f0165150e8618574273143fee'
  ['helpers/ubs_core/go_ast.py']='8742075b0f2f9e10ec0fe37a1641075eaf3480e3f30b7060a306bdff77b84d89'
  ['helpers/ubs_core/go_detectors/__init__.py']='70cc7219036b6d704d9a9e9414c623b4d0eb65ef26e12aac19c8ba6aa055ba41'
  ['helpers/ubs_core/go_detectors/archive_extraction.py']='f57f33494fed091791358f3ccfa1040df43a8a0c39801fc533b2beebcfcd8181'
  ['helpers/ubs_core/go_detectors/cookie_security.py']='c2d6d4e0708c972b71c52627a3211525bc17ab448e68de9b556d3090585997f4'
  ['helpers/ubs_core/go_detectors/cors_credentials.py']='9af32be5bcae4bc051229d835bf21fdce20973746a2669ccb00dffc1261df401'
  ['helpers/ubs_core/go_detectors/hardcoded_secrets.py']='be700a8f5043b050895327a664696886baeb728e969a56ca820e8f5c1c9cb623'
  ['helpers/ubs_core/go_detectors/header_injection.py']='5eb25e3cde4ed4ec62e929eb03640640d5a691765c92c674c43fde10a35969c1'
  ['helpers/ubs_core/go_detectors/host_header.py']='9c0f3a41a0350fc5c77df2dcdba0a21792a8e4f56ce7ceddb2adecaf7f8b01a0'
  ['helpers/ubs_core/go_detectors/jwt_verification.py']='5d992745b5a2f1936b1f2f4fab904d977d2f0f981e37cbd29b3a43f4b349a9a9'
  ['helpers/ubs_core/go_detectors/open_redirect.py']='36ad1fd5cdcd4511d9714e32caafe41d32ccd589593208a37eae5cb748a3d08d'
  ['helpers/ubs_core/go_detectors/outbound_url.py']='eaac8bb45a47889dbd015cdd84f7cc16049a6898cecdab62e01a5a469582e100'
  ['helpers/ubs_core/go_detectors/path_traversal.py']='bd81b3c7cccd0a08a36478e6615ecf93eb07ae586926b0968012955836530af8'
  ['helpers/ubs_core/go_detectors/request_body_limit.py']='865d1b5534117160d0718a562748e17d735cc6236078ea5e6af0e681a14cb819'
  ['helpers/ubs_core/go_detectors/request_regex.py']='c7e99ecc7456be7d9a271860d80180ce3e73f814b4db92f7958226d0e3510a59'
  ['helpers/ubs_core/go_detectors/reverse_proxy_ssrf.py']='7fb8d18e9d5afdc3c9503cf30b9e4545fc7818dd963f8873f06f17ff729380bd'
  ['helpers/ubs_core/go_detectors/security_randomness.py']='869d4f62ce4418e6430ab6791facf3aa0cfda26674eb4697aa50a74b1450e17d'
  ['helpers/ubs_core/go_patterns/__init__.py']='30709d223fdb4167cbfa35569eb0ee2d2d3cbbc5fcf4803a2721f8ab41499cc5'
  ['helpers/ubs_core/go_patterns/concurrency_channels.py']='d7a5925f2cdc8aac511f9c5e9ee975b707beb1dee2802563058f32aa10266290'
  ['helpers/ubs_core/go_patterns/errors.py']='5cdca8346078b8d8e9923cb0294575a90049f14b9169bc5025de9123cd8e0c26'
  ['helpers/ubs_core/go_patterns/json_fs.py']='e561c18ac8d49ca7d3a0644381b5624d3d0e5f975c43a3056e4ad177538a7b6b'
  ['helpers/ubs_core/go_patterns/misc.py']='d23874e0fd10bc3538fd0c9b4eae998dbcb3076dd66020a6c764c7bb297506bd'
  ['helpers/ubs_core/go_rules.py']='371ce59903ab8f4e1b4cb948bb5c67790b84df8d1c05498a77b52d835a227a73'
  ['helpers/ubs_core/go_scan.py']='3380820eacff1eb36a92d1a18fb7b042e5f3d1c0bed881cbbd1452cc4be64106'
  ['helpers/ubs_core/io.py']='fc2a9dbd784040482108125c0911e996115fe39be5cb83568e605d2c8243b2d8'
  ['helpers/ubs_core/java_ast.py']='f05d019065f8a4bb6d03e739f3d01eb726c9b0348579bf70508fced3c46e6c3d'
  ['helpers/ubs_core/java_detectors/__init__.py']='ef52ffa7d353633e7bb1d1caa697c3b3bf83c6d7dc1ec111a3a4b71e2aa2d8f0'
  ['helpers/ubs_core/java_detectors/_common.py']='658ef921d7248ee9e95e3dff0887092e1133debe67c2b2b62aa21b7447584c73'
  ['helpers/ubs_core/java_detectors/archive_extraction.py']='d55d79ba241f0ba037c0033b5f18bef7a06cc71865f899508004655091c926ab'
  ['helpers/ubs_core/java_detectors/collections_foreach.py']='eea7650f153c3dc644047cfea0009dfab620a46c75c596900a94111146b2a94c'
  ['helpers/ubs_core/java_detectors/control_flow.py']='7c22d242c21e56fd23b01093bd40cbca00a5f8a9511a3dc3d19d8d8cc9d69e0c'
  ['helpers/ubs_core/java_detectors/equals_hashcode.py']='6647624ef4111703b3bd66e67ec2140efc493508eba1eefa6f72ca43caf15db1'
  ['helpers/ubs_core/java_detectors/header_injection.py']='65a4c8a006759204beed63b62ceedbbc1ae91713f764132005ba7e7232f79112'
  ['helpers/ubs_core/java_detectors/io_loops.py']='9a0c38817e7cc38e59bb36f6248270d3aae8064965804f2694143c05481a42f0'
  ['helpers/ubs_core/java_detectors/optional_get.py']='62ca39904c0af60817dcf946a8766064c6f16c802f18c9bea12f14460e75165a'
  ['helpers/ubs_core/java_detectors/resource_leaks.py']='a4247b9c04b4856b318baaff7f9c7d42512ab24808ff92ca71cfb6079e9551e0'
  ['helpers/ubs_core/java_detectors/runtime_exec.py']='60318317472be27b99923970a007d2899af77e8fb409b70adeb4aab9211fa5e8'
  ['helpers/ubs_core/java_detectors/security_randomness.py']='ec94b240583b902aa356629c909f6709280fa2b2caf38539521a0af18e328d4f'
  ['helpers/ubs_core/java_detectors/sql_concat_fallback.py']='f9f8de97db4b96d7fb6e9869d2213958203574d454f2e55283bd0b18540c7fc6'
  ['helpers/ubs_core/java_detectors/ssrf_outbound_url.py']='f3419263e405533a15bff4f73751ce0695dc3569dcb51490ab7ecd8cf952e1f8'
  ['helpers/ubs_core/java_detectors/streams_concat.py']='4c76d552db8a001b8647f42c6ec20e90e8128e854bf0bcf030eac993b106db4d'
  ['helpers/ubs_core/java_detectors/tech_debt.py']='6fa5702a073d08656b72f9673ba5299770f8f56277d0f942ab7cbc99bcabc873'
  ['helpers/ubs_core/java_patterns/__init__.py']='8b7de6cca7d1b61a2884216d2756adabf3ad7d2a08bea8defe3e8d305452e9c2'
  ['helpers/ubs_core/java_patterns/concurrency_io.py']='9bee9f2911a23993806d3e367339b99af70eaf4946cc979b21d18bc8a35e383d'
  ['helpers/ubs_core/java_patterns/foundations.py']='65cb1a81bc8903742814216430eed68705cde6474f7112e07206753d5cf5827b'
  ['helpers/ubs_core/java_patterns/quality.py']='2e037fbc04bd6d9e0896357612fd6e195ca9aecc1b0ab38934335b297eba0475'
  ['helpers/ubs_core/java_patterns/resource_lifecycle.py']='0a8f38417321c16bbcae6bdf42aa68c15d6f6e3ca6d70a84e3aa29c6f6ac5d1c'
  ['helpers/ubs_core/java_patterns/security_rg.py']='d1ddb0626ec8729133b915dd27401ea2823df452acd18920c2efd919119864fa'
  ['helpers/ubs_core/java_rules.py']='2ded3f1e04858d63ef984ae9c1810f3c83fab36932addca902ca58773eb242c8'
  ['helpers/ubs_core/java_scan.py']='1271ba5994b008c884f24822dc50911f8094b103b764c587744badd9df6534cb'
  ['helpers/ubs_core/js_ast.py']='bbab950335228160ddde9344b6fd1e807085474456de9f33fd7d755d2cc375bd'
  ['helpers/ubs_core/js_patterns/__init__.py']='0529d2e73e888d4ff04bea182fb241f259eee345d04ef3bb19478b74e5353851'
  ['helpers/ubs_core/js_patterns/debug_quality.py']='de6e0c36dfb9e06691b65ec5e8fd7739ec22840ebf5c487801f998218bb78172'
  ['helpers/ubs_core/js_patterns/eq_regex_dom.py']='d2513ecc6d6311612e0ccd02293d25a5373ef60cf4d689f96ec30c4c12cf4d8a'
  ['helpers/ubs_core/js_patterns/fn_parse_perf.py']='1cd06fa7c281e2a26d1979b01008dbea8b900bf6a2444ddc4b016e02362ed89a'
  ['helpers/ubs_core/js_patterns/null_coercion.py']='68a079a324429730c55abfef5752f231021c2484177b7f43e49f287e6f55ba59'
  ['helpers/ubs_core/js_patterns/proto_vars.py']='b4fdf0f9ccfa5b4133f12f53dc2813fcd618530756c9a299ed16e1d0c0388b31'
  ['helpers/ubs_core/js_patterns/security_node.py']='7ceb9d14a629fb7bb89fce5c702a7ccc769260be10feab937a843b473efcf81e'
  ['helpers/ubs_core/js_rules.py']='aef56a2d91a68b9e4aad2586de9d94342555ad74008fb06c0ab10a8142b7eecc'
  ['helpers/ubs_core/js_scan.py']='75f9351e5dcf8da3cd501e28d43e1d2512b2ab9e7833152788ae43579aab52ba'
  ['helpers/ubs_core/kotlin_rules.py']='6dd77c16cd9fbba0e555162e2a8f378858ce70b4d70668f64ec8142983ba3c35'
  ['helpers/ubs_core/kotlin_scan.py']='aefd8e41e88b28c3513794661a765e887a521502f23ea2ff2d3decee1b97974c'
  ['helpers/ubs_core/lexer.py']='5fee42966b78805e287addaa7bb61ddad24e9dc21e4467d0b891ad60fa412396'
  ['helpers/ubs_core/prefilter.py']='3d506606874f165afdc9c723cc7cf844ae148db624d87d862b7276233f13f3ee'
  ['helpers/ubs_core/py_ast.py']='65f04218142f319d77b3aaf19779714303fab261b6f210fb5aeb0ed13a0bc6af'
  ['helpers/ubs_core/py_detectors/__init__.py']='7ff850f4cf568398d6d1791d8ed932271ae685d789083683ae11917e24fd8504'
  ['helpers/ubs_core/py_detectors/archive_extraction.py']='bde3f4b466aa25d5845467df6795fb3a1d15597846ae8440be8ee8fd170b316c'
  ['helpers/ubs_core/py_detectors/command_injection.py']='68db16769a53a677cf0e885f8b04b9596b10a2168b0f7fd1e52c1be256a4e941'
  ['helpers/ubs_core/py_detectors/cookie_security.py']='fba1be4149be8f0de38118fc822114cd7fd016e58b016301cad699d18b24e243'
  ['helpers/ubs_core/py_detectors/cors_misconfig.py']='ddbdd8315a1fd640e8e3e7c0cae8a6d1de01e2a6f279484a269628845540c29c'
  ['helpers/ubs_core/py_detectors/crypto_misuse.py']='cc25433b614058f57c9ec672c05f5d87e63538c3fcc65851ed3abfdb5f7fe2c6'
  ['helpers/ubs_core/py_detectors/csrf_disable.py']='7e79d19bd519d945d4a4df9e21d89f864e29ad2cd98b1bb0594970984345f938'
  ['helpers/ubs_core/py_detectors/debug_host_config.py']='9542f55192935adabf1999506d5db13e11effee156ecb660cf888a207c9b8d12'
  ['helpers/ubs_core/py_detectors/division.py']='2e0c5c23ba82198fd2d2ae2407c7ef88f563238a91cac32a064ef086d8eadf6f'
  ['helpers/ubs_core/py_detectors/email_header_injection.py']='74a24a0777cecb6adc7e1e6b5b42c03cc1a38b4296293466cf217cf0251d1fe0'
  ['helpers/ubs_core/py_detectors/file_permissions.py']='9bb0fd672c9fd3b92071bbb208e11219840e2abf2956ecf83e3185ff1b9199b2'
  ['helpers/ubs_core/py_detectors/hardcoded_secrets.py']='9b04520774cc9646861a04e833ed6a24ea408df24f62c902e0a1c6808dba6995'
  ['helpers/ubs_core/py_detectors/header_injection.py']='c5aaff8ab91018f4df3c048a89b19f6a0b9b4a36c4535f3ae45ae5dbbd2499cd'
  ['helpers/ubs_core/py_detectors/host_header_poisoning.py']='ac14f4db4f35387d5b3fe94bfc15596840cd0dca22f96ef52bbe33400b2e67e5'
  ['helpers/ubs_core/py_detectors/http_timeout.py']='d528642d6aac30103e3f2d3317b0d416921ce065a94b531ad594f459169595a2'
  ['helpers/ubs_core/py_detectors/insecure_random.py']='ccf7b2b917dce383e7d5cb60082f0101203e76cc3976aadfe73d0b9d1a038ade'
  ['helpers/ubs_core/py_detectors/io_open_checks.py']='ed6d844409ee75f00b5d66f67232fd0fd4f272c1f1ae3fc84bb313b838474a10'
  ['helpers/ubs_core/py_detectors/is_literal.py']='b7770eb1c6a28bc5355485dc195f51adf190ef20b19a7d14a72d499f22ba8fc5'
  ['helpers/ubs_core/py_detectors/json_loads.py']='a6b4d32e33fbfb1bd76df1edfa55d259989bb5218dbf6fbfb19c8ee0887ddd39'
  ['helpers/ubs_core/py_detectors/jwt_verification.py']='f384d77bd82df1bea21037b7c47fca4be4d1cff9b41185a1b2746513dbf16e19'
  ['helpers/ubs_core/py_detectors/ldap_injection.py']='31cd80955c932680e5d71e89a3f8d83cfa4de0ef6eb5311b5d4aa7a287d2097f'
  ['helpers/ubs_core/py_detectors/mass_assignment.py']='ad2d9926f406a461fc16591e6f2d9731bdd48f5d0d3a69f4d355a2ddd410469c'
  ['helpers/ubs_core/py_detectors/missing_returns.py']='1aee6c57b5b95af3161e75d8b9cd33e1bdd3422ceaf8e47e4adc33d7e104be2b'
  ['helpers/ubs_core/py_detectors/mutation_during_iteration.py']='50831c50c1536773aeb27481beb2d632e9ce3f906379f592e22e8d27a44a73bd'
  ['helpers/ubs_core/py_detectors/nosql_injection.py']='5117d571e16db684b8dd6d582ac19a9c811baf889d7ed1cc32eece2a35f2197a'
  ['helpers/ubs_core/py_detectors/open_redirect.py']='e8286bdc691f56c657011c66ba3af4a98e5c5709f8e74617b0d63d639c3f6f64'
  ['helpers/ubs_core/py_detectors/password_hashing.py']='191f24ba2fbd5acefa45a70301b83eccb222cbf6d6a77817e4fa04bcb9f50d94'
  ['helpers/ubs_core/py_detectors/path_traversal.py']='b3451c827df549ccff16511433bb3a88f37eff20bf6c1a14be3a9b8bb86bac34'
  ['helpers/ubs_core/py_detectors/redos_regex.py']='b096ec343b96451757fe906c7d14254bf8500c1cc27e7c243013af6677a74aad'
  ['helpers/ubs_core/py_detectors/safe_html_xss.py']='e36f35f8b1ec02e8625a2e7848d67e26d103494501062721548a67d19df9087e'
  ['helpers/ubs_core/py_detectors/security_assert.py']='13b97f54ff9472312b0c0f831256c8f73d699ec743fee1659d127b031f1e0009'
  ['helpers/ubs_core/py_detectors/sql_injection.py']='d47461a041b85334dfbe809e80d58d610e7445081d941203688e55757fff459c'
  ['helpers/ubs_core/py_detectors/ssrf.py']='b6bdbb8d03549146081e61e2c9fd1b28c94276edbf184fa3b67d1d1349e6ba67'
  ['helpers/ubs_core/py_detectors/subprocess_timeout.py']='b102cdc52d47e1ee2de73c3b78660ddec540d77865b2164b6c6f414b7f29a8f4'
  ['helpers/ubs_core/py_detectors/template_autoescape.py']='373544e3181dfaf40c09b0002612951e018d599b395c6fbdb55b8317c1533640'
  ['helpers/ubs_core/py_detectors/template_injection.py']='0fafe6cc4b6944f5c754ac7df3a44810d9a23100e3de1954033b8c42558cd807'
  ['helpers/ubs_core/py_detectors/tls_verification.py']='54d90e5d758bdc27517f05ddbdc9fdf65a0ff1ba5c9941bfac046b5291d3bfa5'
  ['helpers/ubs_core/py_detectors/unsafe_deserialization.py']='c349c0261fda4e5eba221303087e6e131db5dfbd85fe165ff28f7686f84a253f'
  ['helpers/ubs_core/py_detectors/xml_parser_security.py']='c57d0423e3ab7a27d7c7d2262cf0d67d15d8d888ac258c952123eb12f4a032c8'
  ['helpers/ubs_core/py_patterns/__init__.py']='7b9b471217121aa96668386d623d9be7ce5ce25e4866c548c3ac2d135faf768d'
  ['helpers/ubs_core/py_patterns/debug_typing.py']='50257dcef8af20c42b456e24c6cd7752cfd56db0d89fb8a175ca342d76e26e4c'
  ['helpers/ubs_core/py_patterns/flow.py']='76a5ad2a28aebd60fd2d7293cb0e558313d90b6119fb97c474860d324366a577'
  ['helpers/ubs_core/py_patterns/foundations.py']='306891cf0a55775eef6d10d1718a497747b5e4e94707e5d9fe766ceacaafc1e7'
  ['helpers/ubs_core/py_patterns/io_files.py']='cfc4ff45b29fc5e6391024475238113970d828e2d16fb21a10d384d5477c6f41'
  ['helpers/ubs_core/py_patterns/quality.py']='67172bb6c1227370021506baa87108060227e5513be996ab52f48bb38cd4c29b'
  ['helpers/ubs_core/py_patterns/security_rg.py']='6a6812f50b396742ed59a2857777ee3b40a9f405948c7450065e1517794ba246'
  ['helpers/ubs_core/py_rules.py']='0f5799f6da1d11f160d8e485b89862ace75e68736dcdbf21fa7e9cbc894ba1f2'
  ['helpers/ubs_core/py_scan.py']='49b74db18f27116f37b36979674ff68744767b5fa75d25294b10b61725324fad'
  ['helpers/ubs_core/registry.py']='45f598b29e9108dec30bb7340cc3d76952274e8c3c33389f1a3615b9523b2c07'
  ['helpers/ubs_core/ruby_ast.py']='4bb0ecb0f511565d3d6e03346965a2d571b50f49f62920b542cdee539c7be4c3'
  ['helpers/ubs_core/ruby_detectors/__init__.py']='7b5ef3809ebd50136d741ade03d1c56b4b16053753dd79a8d90dd9021ebb0db7'
  ['helpers/ubs_core/ruby_detectors/_common.py']='5229306bddc9653d6aba535903fc2a738ccc7b3b4f2bea548aa5cc4bde3a1864'
  ['helpers/ubs_core/ruby_detectors/archive_extraction.py']='f18248f8821304ae8efa409491af9fa5d067b8285127c8d00e22da8ba43816c3'
  ['helpers/ubs_core/ruby_detectors/frozen_string_literal.py']='8cef7c3646681b746ade6748d66d4e3dc137b01c5005d5797950953a40a31bc7'
  ['helpers/ubs_core/ruby_detectors/json_parse_no_rescue.py']='da8046ad2faba8d291cfac3b6a968d558959b8d0854b07b76b04b56c8baf3a06'
  ['helpers/ubs_core/ruby_detectors/open_redirect.py']='9e9cd1b69ee7b08fdbd567584639899f41e96f8e84f29c2368e5a771ce719e11'
  ['helpers/ubs_core/ruby_detectors/response_header_injection.py']='14b88e2a44a9735d4c0c417381b1fa17c6a0a059a5146dce2be48aea2fab6224'
  ['helpers/ubs_core/ruby_detectors/security_randomness.py']='e77e2b4fb84718b7f7af15f55b15edd485af4bd814d2c6a76a3045d5f373c11f'
  ['helpers/ubs_core/ruby_patterns/__init__.py']='ed3371e10794baa474b5270b57db2f40862a5477ecea49165198b65b3636dc3c'
  ['helpers/ubs_core/ruby_patterns/collections_cmp.py']='745cb22be141e72e2166464108d8bcd9637cde067b45a85737c90ffa15c7a310'
  ['helpers/ubs_core/ruby_patterns/debug_perf.py']='c09e2727a08c0cdaa1e36e930758876339bba5e26c358e05b9d45f427ef45a05'
  ['helpers/ubs_core/ruby_patterns/exceptions.py']='5ba25ef751016ad5c8c1000f2a035decafa59d1159b63f01584fb5ecce79d4f1'
  ['helpers/ubs_core/ruby_patterns/foundations.py']='47bd8dc284c68ec930568c1f4ebeb7a263b5b951ced363abe72ba19cb069ce0c'
  ['helpers/ubs_core/ruby_patterns/parsing_flow.py']='2e5af6d69db7d78adc07b7a0679c23d78124b2a2166a29f0da319d2a5cfe173e'
  ['helpers/ubs_core/ruby_patterns/regex_conc.py']='aba17193a68429bc144c50fd28819b10521c0f50702d65d5ffb9b1f252750b6c'
  ['helpers/ubs_core/ruby_patterns/security_rg.py']='e5258618d34c8d648f0e6e60063e7762e00e0f68765c92096ff9430e5d849d53'
  ['helpers/ubs_core/ruby_patterns/shell_io.py']='65b858569d34639c6e7e7edb59374f9dbd37eef9b0460c588de082af88349b8a'
  ['helpers/ubs_core/ruby_patterns/vars_quality.py']='f68007ffbde60d8e11b574d45815f1f0d8ca6e70eccfa748ce9dc4eb3d6dfd1d'
  ['helpers/ubs_core/ruby_rules.py']='08250a9180ad60bfede06e9a372447e8ee77bba7629ac4283a82adc20f8e486c'
  ['helpers/ubs_core/ruby_scan.py']='01d73954b39f045eccaeb6e935fe80c295b92179127bde2abba6c7b463da4ebd'
  ['helpers/ubs_core/rust_ast.py']='273d1e1eb156a5695a2c4cd46ee311e3ce9b8152849863fb406f27628bfece93'
  ['helpers/ubs_core/rust_detectors/__init__.py']='b238f38c0768683ea44b5bfd8e4e4c8a94e2bbbe98ddd77de32230a47bdd7799'
  ['helpers/ubs_core/rust_detectors/archive_entry_path.py']='92057f297897296d0bc60d2b27f4ddc545c1061b107fef8c5a062668f1a5cccb'
  ['helpers/ubs_core/rust_detectors/async_context.py']='e9aa796dda02f06929c40f27ad8b6bb5fb2dca862e94f211a6c411d96a555c1b'
  ['helpers/ubs_core/rust_detectors/command_executable.py']='ac9f0cdc3a323b807e7079728701b528f3c200757e9e5952905bf307a2077777'
  ['helpers/ubs_core/rust_detectors/cors_credential.py']='f0d29c4ecae87264606a95fcfbae4d83811608f7b24dcc5def4d70d530b308c9'
  ['helpers/ubs_core/rust_detectors/drop_panic.py']='f6686890119f282a67efd6bbc39fb6958850bc46f8cf1ded7c9ff9a6732c0a95'
  ['helpers/ubs_core/rust_detectors/format_literal.py']='132a0e63775fee8cb38efd158ec13fcea176b2d403b3912bc1dc2eb1a62ef7db'
  ['helpers/ubs_core/rust_detectors/hardcoded_secrets.py']='5bf04fb1853d38afd9e9ced9de36d05db9799b0211f8d954ac07a16a89c4c264'
  ['helpers/ubs_core/rust_detectors/host_header_url.py']='3e256b4070030eed7b8a76335c25376d96eed552848472b55243c3ca2c4bd013'
  ['helpers/ubs_core/rust_detectors/jwt_verification.py']='760363535208aa4beac43b5c05bdf182d7624b7cada12e25637b5ac78f188c03'
  ['helpers/ubs_core/rust_detectors/loop_context.py']='b1a9092202797b2d9c84b4562092efed2535b705000cfc386d1224edf0c31bea'
  ['helpers/ubs_core/rust_detectors/open_redirect.py']='2c90a1638018483103766ff0b2f6a406b495619d35eb7be34c67139312c5c812'
  ['helpers/ubs_core/rust_detectors/path_traversal.py']='da7df457452c782089b6771e42dc1d487383971f2a69df48410d933cb89e12f1'
  ['helpers/ubs_core/rust_detectors/request_regex.py']='a8a0a33b2731685696d97d8ffa901f312f24123d7f2b55ae36b58ecfed63f50f'
  ['helpers/ubs_core/rust_detectors/request_url.py']='913a4a50e228d619d014e1a2cc0b96f8c4245b30b26378e7d9b574a6c315f811'
  ['helpers/ubs_core/rust_detectors/response_header.py']='09164f654b81073f4b4d86b6f25268e1edf21e40b194a45985c0c90d5ffb2ae9'
  ['helpers/ubs_core/rust_detectors/security_randomness.py']='e6f289a0c5aeec6f9bb735844a45ec7a8c6091df4b3c3b8f98ab70abd44c7273'
  ['helpers/ubs_core/rust_detectors/sql_injection.py']='d829fd9366a4a70eaa736d8601041920217995fadc580f5ca4a2cbd215226339'
  ['helpers/ubs_core/rust_detectors/temp_file_race.py']='115d140d3cb56786921a9f0171e4669dc05439da296bee0219c082018fc416db'
  ['helpers/ubs_core/rust_detectors/tls_indirect.py']='a24357ffa9b2c3f31427264431a9f5d02a00edc24c8b1da5e408d07792b3994f'
  ['helpers/ubs_core/rust_detectors/unbounded_request_body.py']='0ff7769ea71daf041dfdba0c5c280de1e0bd71dce15dd4bd2710f5f26eb05faf'
  ['helpers/ubs_core/rust_rules.py']='33b7baeded29947da72d6b0ce27bf66b17ba0660ca3a42e1641f41f7a2bbfcdf'
  ['helpers/ubs_core/rust_scan.py']='028e1e2bbe5062e2d49cf1c7f9e542089585bc535a96135b1bd5b01b878152a0'
  ['helpers/ubs_core/scheduler.py']='9d4d936984f308c82d80d108b006a65ccd2eeb1d41e07325b621fc39147a94ed'
  ['helpers/ubs_core/selftest.py']='6ca3dd5e5534edc0b8a10e9aac1f80834f0d79b661c50c28bd00b33eb85bff08'
  ['helpers/ubs_core/shards.py']='cdc6ecab42bd962e65bb1ac1dc5e3f20b87c4d68632617286a2991274c0c98f7'
  ['helpers/ubs_core/suppression.py']='473563fd701199b1e16977cce0e26596ab6bceee1ba824fec0b1dcbda3684b1e'
  ['helpers/ubs_core/swift_ast.py']='25abac8a49c6642d3f47085550afd23f6197961ed5c13b53776456d2999e5378'
  ['helpers/ubs_core/swift_detectors/__init__.py']='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
  ['helpers/ubs_core/swift_detectors/_common.py']='2d990b7b7144af650e7c23cedfb915acee483ef3cd34635e81f1f1e2e6d021be'
  ['helpers/ubs_core/swift_detectors/archive_extraction.py']='766039e6dcd91a406742e50334ffaff55d789576b568275d12afc8687cd5b503'
  ['helpers/ubs_core/swift_detectors/header_injection.py']='04822cc6a72553a035d61aebfec048f10ed0b29ddb3e02641810099a562ace33'
  ['helpers/ubs_core/swift_detectors/outbound_url.py']='e5b399b44cc00257fde5743246961ce679145adf77bd0d80a184856e07041cbc'
  ['helpers/ubs_core/swift_detectors/plist_checks.py']='0bb62c45b4f36e9a75a8c7573d02dbd4627f73f8a2b9703bab322ccec8170728'
  ['helpers/ubs_core/swift_detectors/security_randomness.py']='1493df1991cf312c00060261408fb85e98ecf0aa995733caf303d6999eb99597'
  ['helpers/ubs_core/swift_detectors/shell_execution.py']='89e86901a614588d9a353fb9a355fbe72d2fc376464e71acf06be3848803a512'
  ['helpers/ubs_core/swift_detectors/urlsession_correlation.py']='61fedac6e50d17961551a1b18e70813e255a7d1e52a380a03fd16dca7367026a'
  ['helpers/ubs_core/swift_patterns/__init__.py']='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
  ['helpers/ubs_core/swift_patterns/closures_networking.py']='e9a53395a2ebcce3a6fa6b2271efdd67db47d489eee0457802ca1e874a27db7d'
  ['helpers/ubs_core/swift_patterns/debug_quality.py']='467066b5d51d8e0a523b6271407d36e9c44e2cfa5f15d597159011c81eb3137f'
  ['helpers/ubs_core/swift_patterns/errors_security.py']='93149a14f65aa771ba2ad3e2c6642715623545d366b4fafcab1343cc670cf7c9'
  ['helpers/ubs_core/swift_patterns/foundations.py']='448939e787da3152b3c883164280d14d5d82c1864092427d73553ee69dd53bba'
  ['helpers/ubs_core/swift_patterns/misc_cats.py']='75404cda38814ee17d923f2a0b2779255a9538264842916d29d3e03274252242'
  ['helpers/ubs_core/swift_patterns/threading_perf.py']='edd87e4319828ef70f9e458e8d709cb305750a357479920c9a69aed1e17a20d4'
  ['helpers/ubs_core/swift_rules.py']='ae19424f3b25d31ea71fff1f1fd6f3f8f65c05ef046f7ac85dcde9c17937dbd3'
  ['helpers/ubs_core/swift_scan.py']='90a13af4032a9cd0c0f72433405816bc8f5e126d0dca38366100effd73301ef1'
)

# ubs_resolve_helper [OUT_VAR] REL_PATH
# Resolves a helper asset (e.g. "helpers/resource_lifecycle_py.py").
# - If UBS_VERIFIED_ASSET_DIR is set (by the ubs meta-runner), the helper is
#   resolved from that directory. Falling back to an unverified location is
#   refused (exit 2) unless UBS_ALLOW_UNVERIFIED_HELPERS=1.
# - If UBS_VERIFIED_ASSET_DIR is unset (standalone module execution), the
#   helper is resolved from the module directory and verified against
#   UBS_COMMON_HELPER_CHECKSUMS before execution. A checksum mismatch exits 2
#   with remediation unless UBS_ALLOW_UNVERIFIED_HELPERS=1.
# - Returns 1 if the helper does not exist (optional helper skipped).
ubs_resolve_helper(){
  local _out_var="" _rel=""
  if [[ $# -ge 2 ]]; then
    _out_var="$1"
    _rel="$2"
  else
    _rel="$1"
  fi

  local target=""

  if [[ -n "${UBS_VERIFIED_ASSET_DIR:-}" ]]; then
    if [[ -f "${UBS_VERIFIED_ASSET_DIR}/${_rel}" ]]; then
      target="${UBS_VERIFIED_ASSET_DIR}/${_rel}"
      if [[ -n "$_out_var" ]]; then
        printf -v "$_out_var" '%s' "$target"
      else
        printf '%s\n' "$target"
      fi
      return 0
    fi
    local fallback="${UBS_MODULE_LIB_DIR:-${SCRIPT_DIR:-}}/${_rel}"
    if [[ -f "$fallback" ]]; then
      if [[ "${UBS_ALLOW_UNVERIFIED_HELPERS:-0}" == "1" ]]; then
        printf 'warning: UBS_ALLOW_UNVERIFIED_HELPERS=1: using unverified helper %s at %s\n' "$_rel" "$fallback" >&2
        target="$fallback"
        if [[ -n "$_out_var" ]]; then
          printf -v "$_out_var" '%s' "$target"
        else
          printf '%s\n' "$target"
        fi
        return 0
      fi
      ubs_die "helper '$_rel' found at unverified location ($fallback); refusing to execute (set UBS_ALLOW_UNVERIFIED_HELPERS=1 to override)" 2
    fi
    return 1
  fi

  # Standalone mode: UBS_VERIFIED_ASSET_DIR is unset.
  local base_dir="${UBS_MODULE_LIB_DIR:-${SCRIPT_DIR:-}}"
  if [[ -z "$base_dir" ]]; then
    base_dir="$(cd -- "$(dirname "${BASH_SOURCE[1]}")" 2>/dev/null && pwd)"
  fi
  target="${base_dir}/${_rel}"

  if [[ ! -f "$target" ]]; then
    return 1
  fi

  if [[ "${UBS_ALLOW_UNVERIFIED_HELPERS:-0}" == "1" ]]; then
    printf 'warning: UBS_ALLOW_UNVERIFIED_HELPERS=1: using unverified helper %s\n' "$_rel" >&2
    if [[ -n "$_out_var" ]]; then
      printf -v "$_out_var" '%s' "$target"
    else
      printf '%s\n' "$target"
    fi
    return 0
  fi

  local expected="${UBS_COMMON_HELPER_CHECKSUMS[$_rel]:-${UBS_HELPER_CHECKSUMS[$_rel]:-}}"
  if [[ -z "$expected" ]]; then
    ubs_die "helper '$_rel' has no pinned checksum in verification table; refusing to execute" 2
  fi

  local actual
  if ! actual="$(ubs_sha256_file "$target")"; then
    ubs_die "unable to compute checksum for helper '$target' (install sha256sum, shasum, or openssl)" 2
  fi

  if [[ "$actual" != "$expected" ]]; then
    ubs_die "helper '$_rel' failed checksum verification (expected $expected, got $actual); refusing to execute (run 'ubs doctor --fix' or set UBS_ALLOW_UNVERIFIED_HELPERS=1 to override)" 2
  fi

  if [[ -n "$_out_var" ]]; then
    printf -v "$_out_var" '%s' "$target"
  else
    printf '%s\n' "$target"
  fi
  return 0
}

# ubs_resolve_helpers_dir [OUT_VAR]
# Resolves the helpers directory (for ubs_core / PYTHONPATH).
ubs_resolve_helpers_dir(){
  local _out_var="${1:-}"
  local target=""

  if [[ -n "${UBS_VERIFIED_ASSET_DIR:-}" ]]; then
    if [[ -d "${UBS_VERIFIED_ASSET_DIR}/helpers" ]]; then
      target="${UBS_VERIFIED_ASSET_DIR}/helpers"
      if [[ -n "$_out_var" ]]; then
        printf -v "$_out_var" '%s' "$target"
      else
        printf '%s\n' "$target"
      fi
      return 0
    fi
    local fallback="${UBS_MODULE_LIB_DIR:-${SCRIPT_DIR:-}}/helpers"
    if [[ -d "$fallback" ]]; then
      if [[ "${UBS_ALLOW_UNVERIFIED_HELPERS:-0}" == "1" ]]; then
        printf 'warning: UBS_ALLOW_UNVERIFIED_HELPERS=1: using unverified helpers dir at %s\n' "$fallback" >&2
        target="$fallback"
        if [[ -n "$_out_var" ]]; then
          printf -v "$_out_var" '%s' "$target"
        else
          printf '%s\n' "$target"
        fi
        return 0
      fi
      ubs_die "helpers directory found at unverified location ($fallback); refusing to execute (set UBS_ALLOW_UNVERIFIED_HELPERS=1 to override)" 2
    fi
    return 1
  fi

  local base_dir="${UBS_MODULE_LIB_DIR:-${SCRIPT_DIR:-}}"
  if [[ -z "$base_dir" ]]; then
    base_dir="$(cd -- "$(dirname "${BASH_SOURCE[1]}")" 2>/dev/null && pwd)"
  fi
  target="${base_dir}/helpers"
  if [[ ! -d "$target" ]]; then
    return 1
  fi

  if [[ "${UBS_ALLOW_UNVERIFIED_HELPERS:-0}" != "1" && -d "${target}/ubs_core" ]]; then
    local _core_rel _core_actual _core_expected
    for _core_rel in "${!UBS_COMMON_HELPER_CHECKSUMS[@]}"; do
      if [[ "$_core_rel" == helpers/ubs_core/* && -f "${base_dir}/${_core_rel}" ]]; then
        _core_expected="${UBS_COMMON_HELPER_CHECKSUMS[$_core_rel]}"
        if ! _core_actual="$(ubs_sha256_file "${base_dir}/${_core_rel}")"; then
          ubs_die "unable to compute checksum for '${base_dir}/${_core_rel}'" 2
        fi
        if [[ "$_core_actual" != "$_core_expected" ]]; then
          ubs_die "helper file '$_core_rel' failed checksum verification (expected $_core_expected, got $_core_actual); refusing to execute (run 'ubs doctor --fix' or set UBS_ALLOW_UNVERIFIED_HELPERS=1 to override)" 2
        fi
      fi
    done
  fi

  if [[ -n "$_out_var" ]]; then
    printf -v "$_out_var" '%s' "$target"
  else
    printf '%s\n' "$target"
  fi
  return 0
}

# ── JSON ────────────────────────────────────────────────────────────────────
# json_escape [STRING]: escape for a JSON string body (no surrounding quotes).
# Missing argument and empty string are both fine under `set -u`; with no
# argument stdin is used. Every control character U+0000–U+001F is escaped
# (\n \r \t \b \f by name, the rest as \u00XX); non-ASCII passes through.
json_escape(){
  local s=""
  if [[ $# -gt 0 ]]; then s="${1-}"; else s="$(cat 2>/dev/null || true)"; fi
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  s=${s//$'\n'/\\n}
  s=${s//$'\r'/\\r}
  s=${s//$'\t'/\\t}
  s=${s//$'\b'/\\b}
  s=${s//$'\f'/\\f}
  if [[ "$s" == *[$'\x01'-$'\x1f']* ]]; then
    local out="" ch code
    local i
    for (( i = 0; i < ${#s}; i++ )); do
      ch="${s:i:1}"
      printf -v code '%d' "'$ch"
      if (( code > 0 && code < 32 )); then
        printf -v ch '\\u%04x' "$code"
      fi
      out+="$ch"
    done
    s="$out"
  fi
  printf '%s' "$s"
}

# ── Severity ────────────────────────────────────────────────────────────────
# ubs_normalize_severity NAME: the four severities every module reports.
ubs_normalize_severity(){
  case "${1,,}" in
    critical|crit|error|err|high|fatal|blocker) printf 'critical' ;;
    warning|warn|medium|moderate|important) printf 'warning' ;;
    info|information|note|notice|low|minor|hint|style) printf 'info' ;;
    good|ok|pass|clean|none) printf 'good' ;;
    *) printf 'info' ;;
  esac
}

# ── Output format contract ──────────────────────────────────────────────────
# Modules render text, json and sarif. jsonl and toon are produced by the
# meta-runner from the module's json, so asking a module for them directly is
# a usage error (exit 2) — never a silent fallback to text.
ubs_validate_format(){
  case "${1:-text}" in
    text|json|sarif) return 0 ;;
    jsonl|toon)
      ubs_die "--format=$1 is produced by the meta-runner from this module's json; run 'ubs --format=$1' instead (module formats: text|json|sarif)" 2 ;;
    *)
      ubs_die "unknown --format value: $1 (expected text|json|sarif)" 2 ;;
  esac
}

# ── File listing ────────────────────────────────────────────────────────────
# ubs_list_files DIR [--ext CSV] [--exclude CSV] [--files-from FILE]
# Prints NUL-separated paths (safe for names with spaces or newlines).
#   --ext       comma-separated extensions without dots (js,ts); default: all
#   --exclude   comma-separated directory names or globs to skip
#   --files-from  a file with one path per line (or NUL-separated): only those
#                 that exist under DIR are listed (meta-runner file lists)
# Uses `rg --files -0` (respects .gitignore, skips hidden and binary files
# the way the modules already do) and falls back to `find -print0`.
ubs_list_files(){
  local dir="$1"; shift
  local exts="" excludes="" files_from=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --ext) exts="$2"; shift 2 ;;
      --ext=*) exts="${1#*=}"; shift ;;
      --exclude) excludes="$2"; shift 2 ;;
      --exclude=*) excludes="${1#*=}"; shift ;;
      --files-from) files_from="$2"; shift 2 ;;
      --files-from=*) files_from="${1#*=}"; shift ;;
      *) ubs_die "ubs_list_files: unknown option $1" 2 ;;
    esac
  done
  [[ -d "$dir" ]] || return 0
  if [[ -n "$files_from" && -f "$files_from" ]]; then
    local f
    while IFS= read -r -d '' f || [[ -n "$f" ]]; do
      f="${f%$'\n'}"
      [[ -z "$f" ]] && continue
      if [[ "$f" == /* ]]; then
        [[ -f "$f" ]] && printf '%s\0' "$f"
      elif [[ -f "$dir/$f" ]]; then
        printf '%s\0' "$dir/$f"
      fi
    done < <(tr '\n' '\0' < "$files_from"; printf '\0')
    return 0
  fi
  local -a rg_args=(--files -0 --no-messages)
  local -a find_args=()
  local item
  if [[ -n "$exts" ]]; then
    local -a ext_list
    IFS=',' read -r -a ext_list <<<"$exts"
    for item in "${ext_list[@]}"; do
      item="${item#.}"
      [[ -z "$item" ]] && continue
      rg_args+=(-g "*.${item}")
      if [[ ${#find_args[@]} -eq 0 ]]; then find_args+=( '(' -name "*.${item}" ); else find_args+=( -o -name "*.${item}" ); fi
    done
    [[ ${#find_args[@]} -gt 0 ]] && find_args+=( ')' )
  fi
  local -a prune_args=()
  if [[ -n "$excludes" ]]; then
    local -a ex_list
    IFS=',' read -r -a ex_list <<<"$excludes"
    for item in "${ex_list[@]}"; do
      [[ -z "$item" ]] && continue
      rg_args+=(-g "!${item}")
      prune_args+=( -path "*/${item}" -prune -o -path "*/${item}/*" -prune -o )
    done
  fi
  if command -v rg >/dev/null 2>&1; then
    rg "${rg_args[@]}" -- "$dir" 2>/dev/null
  else
    find "$dir" -xdev "${prune_args[@]}" -type f "${find_args[@]}" -print0 2>/dev/null
  fi
}

# ubs_count_files DIR [options...]: number of files ubs_list_files would list.
ubs_count_files(){
  ubs_list_files "$@" | tr -cd '\0' | wc -c | awk '{print $1+0}'
}
